import time

from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Bloomy_Core
    Package: TestProject.Generated.Tests.BloomyCore
    Test: CreatePaymentEntry_TestCase
    Generated by: Meenal Kardale (meenal.kardale@extrapreneurs-india.com)
    Generated on 05/28/2021, 20:43:56
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="3J0RNM_48lLt_KM5Ab6s6A_HZzddmktVs_HhX77AjTM",
                              project_name="Bloomy_Core",
                              job_name="CreatePaymentEntry_TestCase")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 5. Type 'testautomationuser@bloomstack.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("testautomationuser@bloomstack.com")

    # 6. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 7. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 8. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 9. Click 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.click()

    # 10. Type 'payment e' in 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.send_keys("payment e")

    # 11. Click 'Payment Entry List'
    payment_entry_list = driver.find_element(By.XPATH,
                                             "//li[. = 'Payment Entry List']")
    payment_entry_list.click()

    # 12. Does 'Payment Entry1' contain 'Payment Entry'?
    payment_entry1 = driver.find_element(By.XPATH,
                                         "//div[. = 'Payment Entry']")
    step_output = payment_entry1.text
    assert step_output and ("Payment Entry" in step_output)

    time.sleep(2)
    # 13. Click 'New4'
    new4 = driver.find_element(By.XPATH,
                               "//button[. = 'New']")
    time.sleep(2)
    new4.click()

    # 14. Click 'SELECT7'
    select7 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div[2]/div[1]/select")
    select7.click()

    # 15. Select the 'Internal Transfer' option in 'SELECT7'
    select7 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div[2]/div[1]/select")
    Select(select7).select_by_value("Internal Transfer")

    # 16. Click 'SELECT7'
    select7 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div[2]/div[1]/select")
    select7.click()

    # 17. Click 'INPUT39'
    input39 = driver.find_element(By.XPATH,
                                  "//div[3]/div[2]/div[2]/form/div[2]//input")
    input39.click()

    # 18. Type 'v' in 'INPUT39'
    input39 = driver.find_element(By.XPATH,
                                  "//div[3]/div[2]/div[2]/form/div[2]//input")
    input39.send_keys("v")

    # 19. Click 'VapeCo'
    vapeco = driver.find_element(By.XPATH,
                                 "//strong[. = 'VapeCo']")
    vapeco.click()

    # 20. Click 'INPUT40'
    input40 = driver.find_element(By.XPATH,
                                  "//div[5]/div[2]/div[1]/form//input")
    input40.click()

    # 21. Type '[NONE]' in 'INPUT40'
    input40 = driver.find_element(By.XPATH,
                                  "//div[5]/div[2]/div[1]/form//input")
    input40.send_keys(" ")

    # 22. Click 'HDFC - VC'
    hdfc_vc = driver.find_element(By.XPATH,
                                  "//li[. = 'HDFC - VC']")
    hdfc_vc.click()

    # 23. Click 'INPUT41'
    input41 = driver.find_element(By.XPATH,
                                  "//div[5]/div[2]/div[2]//input")
    input41.click()

    # 24. Type '[NONE]' in 'INPUT41'
    input41 = driver.find_element(By.XPATH,
                                  "//div[5]/div[2]/div[2]//input")
    input41.send_keys(" ")

    # 25. Click 'EPI-Sales-Account1 - VC'
    epi_sales_account1_vc = driver.find_element(By.XPATH,
                                                "//div[1]/div/div[2]/div[1]/div/div/ul/li[. = 'EPI-Sales-Account1 - VC']")
    epi_sales_account1_vc.click()

    # 26. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 27. Click 'INPUT42'
    input42 = driver.find_element(By.XPATH,
                                  "//div[6]/div[2]/div[1]/form/div[1]//input")
    input42.click()

    # 28. Type '3,000.00' in 'INPUT42'
    input42 = driver.find_element(By.XPATH,
                                  "//div[6]/div[2]/div[1]/form/div[1]//input")
    input42.send_keys("3,000.00")

    # 29. Click 'INPUT43'
    input43 = driver.find_element(By.XPATH,
                                  "//div[6]/div[2]/div[2]/form/div[1]//input")
    input43.click()

    # 30. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 31. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 32. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 33. Click 'INPUT44'
    input44 = driver.find_element(By.XPATH,
                                  "//div[10]/div[2]/div[1]/form//input")
    input44.click()

    # 34. Type '123' in 'INPUT44'
    input44 = driver.find_element(By.XPATH,
                                  "//div[10]/div[2]/div[1]/form//input")
    input44.send_keys("123")

    # 35. Click 'INPUT45'
    input45 = driver.find_element(By.XPATH,
                                  "//div[10]/div[2]/div[2]//input")
    input45.click()

    # 36. Click '31'
    _31 = driver.find_element(By.XPATH,
                              "//div[2]/div//div[. = '31']")
    _31.click()

    # 37. Click 'Save17'
    save17 = driver.find_element(By.XPATH,
                                 "//button[. = 'Save']")
    save17.click()

    # 38. Scroll window by ('0','-400')
    driver.execute_script("window.scrollBy(0,-400)")

    # 39. Does 'Draft' contain 'Draft'?
    draft = driver.find_element(By.XPATH,
                                "//span/span[. = 'Draft']")
    step_output = draft.text
    assert step_output and ("Draft" in step_output)

    # 40. Click 'Submit5'
    submit5 = driver.find_element(By.XPATH,
                                  "//button/span[. = 'Submit']")
    submit5.click()

    # 41. Click 'Yes'
    yes = driver.find_element(By.XPATH,
                              "//button[. = 'Yes']")
    yes.click()

    # 42. Does 'Submitted1' contain 'Submitted'?
    submitted1 = driver.find_element(By.XPATH,
                                     "//span/span[. = 'Submitted']")
    step_output = submitted1.text
    assert step_output and ("Submitted" in step_output)

    # 43. Click 'Settings'
    settings = driver.find_element(By.XPATH,
                                   "//span[. = '      Settings']")
    settings.click()

    # 44. Click 'Logout1'
    logout1 = driver.find_element(By.XPATH,
                                  "//a[. = '       Logout']")
    logout1.click()

    # 45. Is 'Login' visible?
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    assert login.is_displayed()
