import time

from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Bloomy_Core
    Package: TestProject.Generated.Tests.BloomyCore
    Test: DeletePurchaseInvoice_TestCase
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 05/26/2021, 11:58:52
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Bloomy_Core",
                              job_name="DeletePurchaseInvoice_TestCase")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Generated By : Rahul."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Is 'Login' visible?
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    assert login.is_displayed()

    # 3. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 4. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 5. Type 'testautomationuser@bloomstack.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("testautomationuser@bloomstack.com")

    # 6. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 7. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 8. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 9. Click 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.click()

    # 10. Type 'purchase' in 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.send_keys("purchase")

    # 11. Click 'Purchase Invoice List3'
    purchase_invoice_list3 = driver.find_element(By.XPATH,
                                                 "//span[. = 'Purchase Invoice List']")
    purchase_invoice_list3.click()

    # 12. Does 'Purchase Invoice8' contain 'Purchase Invoice'?
    purchase_invoice8 = driver.find_element(By.XPATH,
                                            "//div[. = 'Purchase Invoice']")
    step_output = purchase_invoice8.text
    assert step_output and ("Purchase Invoice" in step_output)
    time.sleep(2)

    # 13. Click 'New'
    new = driver.find_element(By.XPATH,
                              "//span[. = 'New']")
    new.click()

    # 14. Click 'SELECT20'
    select20 = driver.find_element(By.XPATH,
                                   "//div[2]/div/div[1]/form//select")
    select20.click()

    # 15. Select the 'ACC-PINV-.YYYY.-' option in 'SELECT20'
    select20 = driver.find_element(By.XPATH,
                                   "//div[2]/div/div[1]/form//select")
    Select(select20).select_by_value("ACC-PINV-.YYYY.-")

    # 16. Click 'SELECT20'
    select20 = driver.find_element(By.XPATH,
                                   "//div[2]/div/div[1]/form//select")
    select20.click()

    # 17. Click 'INPUT80'
    input80 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div[1]/form/div[4]//input")
    input80.click()

    # 18. Click 'P58'
    p58 = driver.find_element(By.XPATH,
                              "//div/div/div/ul/li[9]//p")
    p58.click()

    # 19. Does 'DIV47' contain '[NONE]'?
    div47 = driver.find_element(By.XPATH,
                                "//div[3]/div[1]/div/div/div[1]/h1/div[2]")
    step_output = div47.text
    assert step_output and ("" in step_output)

    # 20. Get text from 'INPUT80'
    # captured Supplier Name Status Not saved
    input80 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div[1]/form/div[4]//input")
    step_output = input80.get_attribute("value")

    # 21. Scroll window by ('0','300')
    driver.execute_script("window.scrollBy(0,300)")

    # 22. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 23. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 24. Scroll window by ('0','200')
    driver.execute_script("window.scrollBy(0,200)")

    # 25. Click 'DIV51'
    div51 = driver.find_element(By.XPATH,
                                "//div[3]/div/div[2]/div[2]/div[1]/div/div/div[2]")
    div51.click()

    # 26. Click 'VC-RM-FO-0001'
    vc_rm_fo_0001 = driver.find_element(By.XPATH,
                                        "//strong[. = 'VC-RM-FO-0001']")
    vc_rm_fo_0001.click()

    # 27. Click 'Save20'
    save20 = driver.find_element(By.XPATH,
                                 "//span[. = 'Save']")
    save20.click()

    # 28. Scroll window by ('0','-700')
    driver.execute_script("window.scrollBy(0,-700)")

    # 29. Does 'Saved12' contain 'Saved'?
    saved12 = driver.find_element(By.XPATH,
                                  "//div[. = 'Saved']")
    step_output = saved12.text
    assert step_output and ("Saved" in step_output)

    # 30. Click 'Purchase Invoice2'
    purchase_invoice2 = driver.find_element(By.XPATH,
                                            "//li[2]/a[. = 'Purchase Invoice']")
    purchase_invoice2.click()
    time.sleep(2)

    # 31. Click 'INPUT78'
    input78 = driver.find_element(By.XPATH,
                                  "(//input[@class='level-item list-row-checkbox hidden-xs'])[1]")
    driver.execute_script( "arguments[0].click();", input78 )

    # 32. Click 'SPAN8'
    span8 = driver.find_element(By.XPATH,
                                "//div[2]/div[1]/div/div/div[2]/div[2]/button/span/span[2]")
    span8.click()

    # 33. Click 'Delete2'
    delete2 = driver.find_element(By.XPATH,
                                  "//a[. = '\n\t\t\t\tDelete']")
    delete2.click()

    # 34. Click 'Yes'
    yes = driver.find_element(By.XPATH,
                              "//button[. = 'Yes']")
    yes.click()

    # 35. Click 'Settings'
    settings = driver.find_element(By.XPATH,
                                   "//span[. = '      Settings']")
    settings.click()

    # 36. Click 'Logout'
    logout = driver.find_element(By.XPATH,
                                 "//a[. = '       Logout']")
    logout.click()

    # 37. Is 'Login' visible?
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    assert login.is_displayed()
