import time

from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Bloomy_Core
    Package: TestProject.Generated.Tests.BloomyCore
    Test: CreateQuotation_TestCase
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 05/26/2021, 14:11:13
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Bloomy_Core",
                              job_name="CreateQuotation_TestCase")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Generated By : Rahul."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Is 'Login' visible?
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    assert login.is_displayed()

    # 3. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 4. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 5. Type 'testautomationuser@bloomstack.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("testautomationuser@bloomstack.com")

    # 6. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 7. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 8. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 9. Click 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.click()

    # 10. Type 'quotat' in 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.send_keys("quotat")

    # 11. Click 'Quotation List3'
    quotation_list3 = driver.find_element(By.XPATH,
                                          "//p[. = 'Quotation List']")
    quotation_list3.click()

    # 12. Does 'Quotation9' contain 'Quotation'?
    quotation9 = driver.find_element(By.XPATH,
                                     "//div[. = 'Quotation']")
    step_output = quotation9.text
    assert step_output and ("Quotation" in step_output)
    time.sleep(2)

    # 13. Click 'New'
    new = driver.find_element(By.XPATH,
                              "//span[. = 'New']")
    new.click()

    # 14. Click 'INPUT141'
    input141 = driver.find_element(By.XPATH,
                                   "//div[2]/form/div[2]/div/div[2]/div[1]/div//input")
    input141.click()

    # 15. Type 'vap' in 'INPUT141'
    input141 = driver.find_element(By.XPATH,
                                   "//div[2]/form/div[2]/div/div[2]/div[1]/div//input")
    input141.send_keys("vap")

    # 16. Click 'VapeCo6'
    vapeco6 = driver.find_element(By.XPATH,
                                  "//strong[. = 'VapeCo']")
    vapeco6.click()

    # 17. Click 'INPUT142'
    input142 = driver.find_element(By.XPATH,
                                   "//div[1]/form/div[4]//input")
    input142.click()

    # 18. Click 'INPUT142'
    input142 = driver.find_element(By.XPATH,
                                   "//div[1]/form/div[4]//input")
    input142.click()

    # 19. Click 'P55'
    p55 = driver.find_element(By.XPATH,
                              "//div[4]/div/div[2]/div[1]/div/div/ul/li[1]//p")
    p55.click()

    # 20. Scroll window by ('0','300')
    driver.execute_script("window.scrollBy(0,300)")

    # 21. Scroll window by ('0','-57')
    driver.execute_script("window.scrollBy(0,-57)")

    # 22. Scroll window by ('0','-100')
    driver.execute_script("window.scrollBy(0,-100)")

    # 23. Click 'INPUT143'
    input143 = driver.find_element(By.XPATH,
                                   "//div[4]/div/div[2]/div/input")
    input143.click()

    # 24. Click 'svg3'
    svg3 = driver.find_element(By.XPATH,
                               "//div[3]/nav/div[3]/*")
    svg3.click()

    # 25. Click 'svg3'
    svg3 = driver.find_element(By.XPATH,
                               "//div[3]/nav/div[3]/*")
    svg3.click()

    # 26. Click '3013'
    _3013 = driver.find_element(By.XPATH,
                                "//div[34][. = '30']")
    _3013.click()

    # 27. Scroll window by ('0','199')
    driver.execute_script("window.scrollBy(0,199)")

    # 28. Scroll window by ('0','200')
    driver.execute_script("window.scrollBy(0,200)")

    # 29. Click 'Add Row'
    add_row = driver.find_element(By.XPATH,
                                  "//div[6]//button[. = '\n\t\t\t\t\t\t\tAdd Row']")
    add_row.click()

    # 30. Click 'DIV84'
    div84 = driver.find_element(By.XPATH,
                                "//form/div/div/div[2]/div[2]/div[1]/div/div/div[2]")
    div84.click()

    # 31. Click 'Finished Oil, Dry Goods, Extracted Ja...2'
    finished_oil_dry_goods_extracted_ja_2 = driver.find_element(By.XPATH,
                                                                "//span[. = 'Finished Oil, Dry Goods, Extracted Jack Herer Cannabis Oil']")
    finished_oil_dry_goods_extracted_ja_2.click()

    # 32. Does 'DIV47' contain '[NONE]'?
    div47 = driver.find_element(By.XPATH,
                                "//div[3]/div[1]/div/div/div[1]/h1/div[2]")
    step_output = div47.text
    assert step_output and ("" in step_output)

    # 33. Get text from 'Item Code'
    # Captured Item status not saved
    item_code = driver.find_element(By.XPATH,
                                    "//input[@placeholder = 'Item Code']")
    step_output = item_code.get_attribute("value")

    # 34. Click 'Save26'
    save26 = driver.find_element(By.XPATH,
                                 "//span[. = 'Save']")
    driver.execute_script( "arguments[0].click();", save26 )

    # 35. Scroll window by ('0','-542')
    driver.execute_script("window.scrollBy(0,-542)")

    # 36. Click 'Close3'
    close3 = driver.find_element(By.XPATH,
                                 "//span[. = 'Close']")
    close3.click()

    # 37. Does 'Saved5' contain 'Saved'?
    saved5 = driver.find_element(By.XPATH,
                                 "//div[. = 'Saved']")
    step_output = saved5.text
    assert step_output and ("Saved" in step_output)

    # 38. Does 'DIV47' contain '[NONE]'?
    div47 = driver.find_element(By.XPATH,
                                "//div[3]/div[1]/div/div/div[1]/h1/div[2]")
    step_output = div47.text
    assert step_output and ("" in step_output)

    # 39. Click 'Submit13'
    submit13 = driver.find_element(By.XPATH,
                                   "//button/span[. = 'Submit']")
    submit13.click()

    # 40. Click 'Yes3'
    yes3 = driver.find_element(By.XPATH,
                               "//button[. = 'Yes']")
    yes3.click()

    # 41. Click 'Close2'
    close2 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\tClose\n\t\t\t\t\t\t\t\t']")
    close2.click()

    # 42. Does 'Quotation has been submitted successf...5' contain 'Quotation has been submitted successfully'?
    quotation_has_been_submitted_successf_5 = driver.find_element(By.XPATH,
                                                                  "//div[. = 'Quotation has been submitted successfully']")
    step_output = quotation_has_been_submitted_successf_5.text
    assert step_output and (
        "Quotation has been submitted successfully" in step_output)

    # 43. Click 'Settings2'
    settings2 = driver.find_element(By.XPATH,
                                    "//span[. = '      Settings']")
    settings2.click()

    # 44. Click 'Logout1'
    logout1 = driver.find_element(By.XPATH,
                                  "//a[. = '       Logout']")
    logout1.click()

    # 45. Does 'Login' contain 'Login'?
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    step_output = login.text
    assert step_output and ("Login" in step_output)
