from addons.random_data_generator import RandomDataGenerator
from addons.string_utils import StringUtils
from distutils.util import strtobool
from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
from subtests import test_login
from subtests import test_logout
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Bloomy_Core
    Package: TestProject.Generated.Tests.BloomyCore
    Test: LeadToInvestor_TestCase1
    Generated by: Meenal Kardale (meenal.kardale@extrapreneurs-india.com)
    Generated on 06/30/2021, 10:46:59
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="3J0RNM_48lLt_KM5Ab6s6A_HZzddmktVs_HhX77AjTM",
                              project_name="Bloomy_Core",
                              job_name="LeadToInvestor_TestCase1")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """1. Go to the lead doctype.(Desk>> CRM>>Lead) or Type \"Lead in search bar\"\".

    2. Open Lead.3. Click on create Button in top right corner and select Investor.  It will redirect you to on Investor doctype.4. Save.
    """
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"
    ExpectedLeadName = ""
    ActualLeadName = ""
    ExpectedLeadID = ""
    ActualLeadIDPartyNmOnInvest = ""
    ActualLeadNmonInvestor = ""
    username = ""
    pwd = ""
    RandomLeadName = ""

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Login to the Application
    test_login.test_main(driver)

    # 3. Click 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.click()

    # 4. Type 'lead lis' in 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.send_keys("lead lis")

    # 5. Click 'Lead List'
    lead_list = driver.find_element(By.XPATH,
                                    "//li[. = 'Lead List']")
    lead_list.click()

    # 6. Does 'Lead7' contain 'Lead'?
    lead7 = driver.find_element(By.XPATH,
                                "//div[. = 'Lead']")
    step_output = lead7.text
    assert step_output and ("Lead" in step_output)

    # 7. Click 'New4'
    new4 = driver.find_element(By.XPATH,
                               "//button[. = 'New']")
    new4.click()

    # 8. Does 'New Lead 11' contain 'New Lead 1'?
    new_lead_11 = driver.find_element(By.XPATH,
                                      "//div[. = 'New Lead 1']")
    step_output = new_lead_11.text
    assert step_output and ("New Lead 1" in step_output)

    # 9. Does 'Not Saved' contain 'Not Saved'?
    not_saved = driver.find_element(By.XPATH,
                                    "//span/span[. = 'Not Saved']")
    step_output = not_saved.text
    assert step_output and ("Not Saved" in step_output)

    # 10. Click 'INPUT64'
    input64 = driver.find_element(By.XPATH,
                                  "//div[4]/div[2]/div[1]/form/div[2]//input")
    input64.click()

    # 11. Generate random name
    step_output = driver.addons().execute(
        RandomDataGenerator.generatename(
        ))
    RandomLeadName = step_output

    # 12. Type '{RandomLeadName}' in 'INPUT64'
    input64 = driver.find_element(By.XPATH,
                                  "//div[4]/div[2]/div[1]/form/div[2]//input")
    input64.send_keys(f'{RandomLeadName}')

    # 13. Get text from 'INPUT64'
    input64 = driver.find_element(By.XPATH,
                                  "//div[4]/div[2]/div[1]/form/div[2]//input")
    step_output = input64.get_attribute("value")
    ExpectedLeadName = step_output

    # 14. Click 'INPUT67'
    input67 = driver.find_element(By.XPATH,
                                  "//div[7]/div[2]/div[1]/form/div[1]//input")
    input67.click()

    # 15. Type 'Add Title Test' in 'INPUT67'
    input67 = driver.find_element(By.XPATH,
                                  "//div[7]/div[2]/div[1]/form/div[1]//input")
    input67.send_keys("Add Title Test")

    # 16. Click 'INPUT68'
    input68 = driver.find_element(By.XPATH,
                                  "//div[7]/div[2]/div[1]/form/div[2]//input")
    input68.click()

    # 17. Type 'Add1' in 'INPUT68'
    input68 = driver.find_element(By.XPATH,
                                  "//div[7]/div[2]/div[1]/form/div[2]//input")
    input68.send_keys("Add1")

    # 18. Click 'INPUT69'
    input69 = driver.find_element(By.XPATH,
                                  "//div[7]/div[2]/div[1]/form/div[3]//input")
    input69.click()

    # 19. Type 'Add2' in 'INPUT69'
    input69 = driver.find_element(By.XPATH,
                                  "//div[7]/div[2]/div[1]/form/div[3]//input")
    input69.send_keys("Add2")

    # 20. Click 'INPUT70'
    input70 = driver.find_element(By.XPATH,
                                  "//div[7]/div[2]/div[1]/form/div[4]//input")
    input70.click()

    # 21. Type 'mumbai' in 'INPUT70'
    input70 = driver.find_element(By.XPATH,
                                  "//div[7]/div[2]/div[1]/form/div[4]//input")
    input70.send_keys("mumbai")

    # 22. Click 'INPUT71'
    input71 = driver.find_element(By.XPATH,
                                  "//div[7]/div[2]/div[1]/form/div[5]//input")
    input71.click()

    # 23. Type 'india' in 'INPUT71'
    input71 = driver.find_element(By.XPATH,
                                  "//div[7]/div[2]/div[1]/form/div[5]//input")
    input71.send_keys("india")

    # 24. Click 'INPUT72'
    input72 = driver.find_element(By.XPATH,
                                  "//div[7]/div[2]/div[2]/form/div[1]//input")
    input72.click()

    # 25. Type 'maharastra' in 'INPUT72'
    input72 = driver.find_element(By.XPATH,
                                  "//div[7]/div[2]/div[2]/form/div[1]//input")
    input72.send_keys("maharastra")

    # 26. Click 'INPUT73'
    input73 = driver.find_element(By.XPATH,
                                  "//div[7]/div[2]/div[2]/form/div[2]//input")
    input73.click()

    # 27. Clear 'ClearText' contents
    cleartext = driver.find_element(By.XPATH,
                                    "//div[7]/div[2]/div[2]/form/div[2]//input")
    cleartext.clear()

    # 28. Type 'india' in 'INPUT73'
    input73 = driver.find_element(By.XPATH,
                                  "//div[7]/div[2]/div[2]/form/div[2]//input")
    input73.send_keys("india")

    # 29. Click 'India'
    india = driver.find_element(By.XPATH,
                                "//li[. = 'India']")
    india.click()

    # 30. Click 'INPUT74'
    input74 = driver.find_element(By.XPATH,
                                  "//div[2]/form/div[3]/div/div[2]/div/input")
    input74.click()

    # 31. Type '40066' in 'INPUT74'
    input74 = driver.find_element(By.XPATH,
                                  "//div[2]/form/div[3]/div/div[2]/div/input")
    input74.send_keys("40066")

    # 32. Click 'INPUT75'
    input75 = driver.find_element(By.XPATH,
                                  "//div[8]/div[2]/div/form/div[1]//input")
    input75.click()

    # 33. Type '2222333345' in 'INPUT75'
    input75 = driver.find_element(By.XPATH,
                                  "//div[8]/div[2]/div/form/div[1]//input")
    input75.send_keys("2222333345")

    # 34. Click 'INPUT76'
    input76 = driver.find_element(By.XPATH,
                                  "//div[8]/div[2]/div/form/div[2]//input")
    input76.click()

    # 35. Type '8765657654' in 'INPUT76'
    input76 = driver.find_element(By.XPATH,
                                  "//div[8]/div[2]/div/form/div[2]//input")
    input76.send_keys("8765657654")

    # 36. Click 'INPUT77'
    input77 = driver.find_element(By.XPATH,
                                  "//div[8]/div[2]/div/form/div[3]//input")
    input77.click()

    # 37. Type '4321' in 'INPUT77'
    input77 = driver.find_element(By.XPATH,
                                  "//div[8]/div[2]/div/form/div[3]//input")
    input77.send_keys("4321")

    # 38. Click 'clicksa'
    clicksa = driver.find_element(By.XPATH,
                                  "//button[. = 'Save']")
    clicksa.click()

    # 39. Click 'clicksabutton'
    clicksabutton = driver.find_element(By.XPATH,
                                        "//button[. = 'Save']")
    clicksabutton.click()

    # 40. Get text from 'PerName'
    pername = driver.find_element(By.XPATH,
                                  "//h1//div[. = 'PerName']")
    step_output = pername.get_attribute("value")
    ActualLeadName = step_output

    # 41. Does 'Lead8' contain 'Lead'?
    lead8 = driver.find_element(By.XPATH,
                                "//span/span[. = 'Lead']")
    step_output = lead8.text
    assert step_output and ("Lead" in step_output)

    # 42. Get text from 'CRM-LEAD-2021-00374'
    crm_lead_2021_00374 = driver.find_element(By.XPATH,
                                              "//h6[. = 'CRM-LEAD-2021-00374']")
    step_output = crm_lead_2021_00374.get_attribute("value")
    ExpectedLeadID = step_output

    # 43. Click 'Create'
    create = driver.find_element(By.XPATH,
                                 "//button[. = '\t\t\t\tCreate ']")
    create.click()

    # 44. Click 'Investor'
    investor = driver.find_element(By.XPATH,
                                   "//li/a[. = 'Investor']")
    investor.click()

    # 45. Click 'INPUT99'
    input99 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div[1]/form/div[2]//input")
    input99.click()

    # 46. Get text from 'INPUT100'
    input100 = driver.find_element(By.XPATH,
                                   "//div[2]/div/div[2]/form//input")
    step_output = input100.get_attribute("value")
    ActualLeadIDPartyNmOnInvest = step_output

    # 47. Click 'Save19'
    save19 = driver.find_element(By.XPATH,
                                 "//div[4]//button[. = 'Save']")
    save19.click()

    # 48. Is 'Saved3' present?
    saved3 = driver.find_element(By.XPATH,
                                 "//div[3]/div[. = 'Saved']")

    # 49. Get text from 'PerName1'
    pername1 = driver.find_element(By.XPATH,
                                   "//div[4]/div[1]//div[. = 'PerName']")
    step_output = pername1.get_attribute("value")
    ActualLeadNmonInvestor = step_output

    # 50. Compares '{ExpectedLeadName}' with '{ActualLeadName}'
    step_output = driver.addons().execute(
        StringUtils.comparetwostrings(
            firstString=f'{ExpectedLeadName}',
            secondString=f'{ActualLeadName}',
            ignoreCase=False,
            expectedResult=0))

    # 51. Compares '{ExpectedLeadName}' with '{ActualLeadNmonInvestor}'
    step_output = driver.addons().execute(
        StringUtils.comparetwostrings(
            firstString=f'{ExpectedLeadName}',
            secondString=f'{ActualLeadNmonInvestor}',
            ignoreCase=False,
            expectedResult=0))

    # 52. Compares '{ExpectedLeadID}' with '{ActualLeadIDPartyNmOnInvest}'
    step_output = driver.addons().execute(
        StringUtils.comparetwostrings(
            firstString=f'{ExpectedLeadID}',
            secondString=f'{ActualLeadIDPartyNmOnInvest}',
            ignoreCase=False,
            expectedResult=0))

    # 53. Click 'Save19'
    save19 = driver.find_element(By.XPATH,
                                 "//div[4]//button[. = 'Save']")
    save19.click()

    # 54. Logout from the application
    test_logout.test_main(driver)
