import time

from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Bloomy_Core
    Package: TestProject.Generated.Tests.BloomyCore
    Test: DeletePackageTag_TestCase02
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 05/17/2021, 10:56:08
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Bloomy_Core",
                              job_name="DeletePackageTag_TestCase02")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Is 'Login' visible?
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    assert login.is_displayed()

    # 3. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 4. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 5. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("rahul.prakash@extrapreneursindia.com")

    # 6. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 7. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 8. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 9. Click 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.click()

    # 10. Type 'Package Tag' in 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.send_keys("Package Tag")

    # 11. Click 'Package Tag1'
    package_tag1 = driver.find_element(By.XPATH,
                                       "//li[2]//b[. = 'Package Tag']")
    package_tag1.click()

    # 12. Is 'Package Tag2' present?
    package_tag2 = driver.find_element(By.XPATH,
                                       "//div[. = 'Package Tag']")
    time.sleep(2)

    # 13. Click 'New1'
    new1 = driver.find_element(By.XPATH,
                               "//span[. = 'New']")
    new1.click()
    time.sleep( 2 )

    # 14. Click 'INPUT75'
    input75 = driver.find_element(By.XPATH,
                                  "//form/div[1]/div/div//input")
    input75.click()

    # 15. Type 'va' in 'INPUT75'
    input75 = driver.find_element(By.XPATH,
                                  "//form/div[1]/div/div//input")
    input75.send_keys("va")
    time.sleep(2)

    # 16. Click 'VapeCo'
    vapeco = driver.find_element(By.XPATH,
                                 "//strong[. = 'VapeCo']")
    vapeco.click()
    time.sleep( 2 )

    # 17. Click 'INPUT76'
    input76 = driver.find_element(By.XPATH,
                                  "//form/div[2]//input")
    input76.click()

    # 18. Type '7576578465' in 'INPUT76'
    input76 = driver.find_element(By.XPATH,
                                  "//form/div[2]//input")
    input76.send_keys("7576578465")

    # 19. Is 'New Package Tag2' visible?
    new_package_tag2 = driver.find_element(By.XPATH,
                                           "//h4[. = 'New Package Tag']")
    assert new_package_tag2.is_displayed()

    # 20. Click 'Save12'
    save12 = driver.find_element(By.XPATH,
                                 "//button[. = 'Save']")
    save12.click()
    time.sleep( 2 )


    # 21. Click 'INPUT77'
    input77 = driver.find_element(By.XPATH,
                                  "//div[2]/div[2]/div/div[1]/div/input")
    input77.click()
    time.sleep( 2 )

    # 22. Click 'Actions5'
    actions5 = driver.find_element(By.XPATH,
                                   "//span[. = 'Actions']")
    actions5.click()

    # 23. Click 'Delete5'
    delete5 = driver.find_element(By.XPATH,
                                  "//span[. = 'Delete']")
    delete5.click()

    # 24. Click 'Yes'
    yes = driver.find_element(By.XPATH,
                              "//button[. = 'Yes']")
    yes.click()

    # 25. Click 'Settings1'
    settings1 = driver.find_element(By.XPATH,
                                    "//span[. = '      Settings']")
    settings1.click()

    # 26. Click 'Logout'
    logout = driver.find_element(By.XPATH,
                                 "//a[. = '       Logout']")
    logout.click()

    # 27. Is 'Cannabis Vapour Pen' present?
    cannabis_vapour_pen = driver.find_element(By.XPATH,
                                              "//h1[1][. = 'Cannabis Vapour Pen']")
