import time

from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Bloomy_Core
    Package: TestProject.Generated.Tests.BloomyCore
    Test: DeleteMaterialrequest_TestCase
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 05/27/2021, 02:47:45
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Bloomy_Core",
                              job_name="DeleteMaterialrequest_TestCase")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Generated By : Rahul."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Is 'Login' visible?
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    assert login.is_displayed()

    # 3. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 4. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 5. Type 'testautomationuser@bloomstack.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("testautomationuser@bloomstack.com")

    # 6. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 7. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 8. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 9. Click 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.click()

    # 10. Type 'mat' in 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.send_keys("mat")

    # 11. Click 'Material Request List2'
    material_request_list2 = driver.find_element(By.XPATH,
                                                 "//li[. = 'Material Request List']")
    material_request_list2.click()

    # 12. Does 'Material Request5' contain 'Material Request'?
    material_request5 = driver.find_element(By.XPATH,
                                            "//div[. = 'Material Request']")
    step_output = material_request5.text
    assert step_output and ("Material Request" in step_output)
    time.sleep(2)

    # 13. Click 'New'
    new = driver.find_element(By.XPATH,
                              "//span[. = 'New']")
    new.click()

    # 14. Does 'DIV47' contain '[NONE]'?
    div47 = driver.find_element(By.XPATH,
                                "//div[3]/div[1]/div/div/div[1]/h1/div[2]")
    step_output = div47.text
    assert step_output and ("" in step_output)

    # 15. Click 'INPUT73'
    input73 = driver.find_element(By.XPATH,
                                  "//div[2]/form/div[1]/div/div[2]/div/input")
    input73.click()

    # 16. Click 'svg'
    svg = driver.find_element(By.XPATH,
                              "//div[1]/nav/div[3]/*")
    svg.click()

    # 17. Click 'svg'
    svg = driver.find_element(By.XPATH,
                              "//div[1]/nav/div[3]/*")
    svg.click()

    # 18. Click '3027'
    _3027 = driver.find_element(By.XPATH,
                                "//div[34][. = '30']")
    _3027.click()

    # 19. Click 'INPUT74'
    input74 = driver.find_element(By.XPATH,
                                  "//div[2]/form/div[2]//input")
    input74.click()

    # 20. Type 'vap' in 'INPUT74'
    input74 = driver.find_element(By.XPATH,
                                  "//div[2]/form/div[2]//input")
    input74.send_keys("vap")

    # 21. Click 'VapeCo19'
    vapeco19 = driver.find_element(By.XPATH,
                                   "//li[. = 'VapeCo']")
    vapeco19.click()

    # 22. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 23. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 24. Click 'DIV48'
    div48 = driver.find_element(By.XPATH,
                                "//div[2]/div/div[2]/div[2]/div[1]/div/div/div[2]")
    div48.click()

    # 25. Click 'P59'
    p59 = driver.find_element(By.XPATH,
                              "//div[1]/div/div/div/ul/li[1]/a/p")
    p59.click()

    # 26. Click 'Save22'
    save22 = driver.find_element(By.XPATH,
                                 "//button[. = 'Save']")
    save22.click()

    # 27. Scroll window by ('0','-200')
    driver.execute_script("window.scrollBy(0,-200)")

    # 28. Click 'Close8'
    close8 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\tClose\n\t\t\t\t\t\t\t\t']")
    close8.click()

    # 29. Does 'Saved9' contain 'Saved'?
    saved9 = driver.find_element(By.XPATH,
                                 "//div[. = 'Saved']")
    step_output = saved9.text
    assert step_output and ("Saved" in step_output)

    # 30. Click 'Material Request3'
    material_request3 = driver.find_element(By.XPATH,
                                            "//li[2]/a[. = 'Material Request']")
    material_request3.click()
    time.sleep(2)

    # 31. Click 'INPUT81'
    input81 = driver.find_element(By.XPATH,
                                  "(//input[@class='level-item list-row-checkbox hidden-xs'])[1]")
    driver.execute_script( "arguments[0].click();", input81)

    # 32. Click 'SPAN9'
    span9 = driver.find_element(By.XPATH,
                                "//div[2]/div[1]/div/div/div[2]/div[2]/button/span[1]")
    span9.click()

    # 33. Click 'Delete2'
    delete2 = driver.find_element(By.XPATH,
                                  "//a[. = '\n\t\t\t\tDelete']")
    delete2.click()

    # 34. Click 'Yes5'
    yes5 = driver.find_element(By.XPATH,
                               "//button[. = 'Yes']")
    yes5.click()

    # 35. Click 'Settings'
    settings = driver.find_element(By.XPATH,
                                   "//span[. = '      Settings']")
    settings.click()

    # 36. Click 'Logout'
    logout = driver.find_element(By.XPATH,
                                 "//a[. = '       Logout']")
    logout.click()

    # # 37. Is 'Login' visible?
    # login = driver.find_element(By.XPATH,
    #                             "//a[. = 'Login']")
    # assert login.is_displayed()
