import time

from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
from password_generator import PasswordGenerator
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Bloomy_Core
    Package: TestProject.Generated.Tests.BloomyCore
    Test: UpdatePackageTag_TestCase
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 05/27/2021, 11:52:37
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Bloomy_Core",
                              job_name="UpdatePackageTag_TestCase")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()




def getPassword():
        pwo = PasswordGenerator()
        pwo.minlen = 8
        # pwo.shuffle_password( 'sdafasdfu', 20 )
        pwo.minuchars = 0  # (Optional)
        pwo.minlchars = 8  # (Optional)
        pwo.minnumbers = 0  # (Optional)
        pwo.minschars = 0  # (Optional)
        # pwo.excludenumbers = "012345"  # (Optional)
        # pwo.excludeschars = "!$%^.()"  # (Optional)
        password = pwo.generate()
        return password




@report_assertion_errors
def test_main(driver):
    """Generated By :Rahul."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Is 'Login' visible?
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    assert login.is_displayed()

    # 3. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 4. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 5. Type 'testautomationuser@bloomstack.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("testautomationuser@bloomstack.com")

    # 6. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 7. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 8. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 9. Click 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.click()

    # 10. Type 'package' in 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.send_keys("package")

    # 11. Click 'Package Tag List'
    package_tag_list = driver.find_element(By.XPATH,
                                           "//p[. = 'Package Tag List']")
    package_tag_list.click()

    # 12. Does 'Package Tag2' contain 'Package Tag'?
    package_tag2 = driver.find_element(By.XPATH,
                                       "//div[. = 'Package Tag']")
    step_output = package_tag2.text
    assert step_output and ("Package Tag" in step_output)
    time.sleep(2)

    # 13. Click 'New1'
    new1 = driver.find_element(By.XPATH,
                               "//span[. = 'New']")
    new1.click()

    # 14. Click 'INPUT75'
    input75 = driver.find_element(By.XPATH,
                                  "//form/div[1]/div/div//input")
    input75.click()

    # 15. Type 'vap' in 'INPUT75'
    input75 = driver.find_element(By.XPATH,
                                  "//form/div[1]/div/div//input")
    input75.send_keys("vap")

    # 16. Click 'VapeCo15'
    vapeco15 = driver.find_element(By.XPATH,
                                   "//li[. = 'VapeCo']")
    vapeco15.click()

    # 17. Click 'INPUT76'
    input76 = driver.find_element(By.XPATH,
                                  "//form/div[2]//input")
    input76.click()

    # 18. Type 'gergerg' in 'INPUT76'
    input76 = driver.find_element(By.XPATH,
                                  "//form/div[2]//input")

    password = getPassword()
    input76.send_keys(password)

    # 19. Click 'Save12'
    save12 = driver.find_element(By.XPATH,
                                 "//button[. = 'Save']")
    save12.click()
    time.sleep(1)

    # 20. Click 'INPUT77'
    input77 = driver.find_element(By.XPATH,
                                  "(//input[@class='level-item list-row-checkbox hidden-xs'])[1]")
    driver.execute_script( "arguments[0].click();", input77 )

    # 21. Click 'SPAN8'
    span8 = driver.find_element(By.XPATH,
                                "//div[2]/div[2]/button/span[1]")
    span8.click()

    # 22. Click 'Edit1'
    edit1 = driver.find_element(By.XPATH,
                                "//a[. = '\n\t\t\t\tEdit']")
    edit1.click()

    # 23. Click 'SELECT21'
    select21 = driver.find_element(By.XPATH,
                                   "//select")
    select21.click()

    # 24. Select the 'Company' option in 'SELECT21'
    select21 = driver.find_element(By.XPATH,
                                   "//select")
    Select(select21).select_by_value("Company")

    # 25. Click 'SELECT21'
    select21 = driver.find_element(By.XPATH,
                                   "//select")
    select21.click()

    # 26. Click 'INPUT87'
    input87 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div[2]/div[1]/div/div/input")
    input87.click()

    # 27. Click 'Bloom India'
    bloom_india = driver.find_element(By.XPATH,
                                      "//p[. = 'Bloom India']")
    bloom_india.click()

    # 28. Click 'Update'
    update = driver.find_element(By.XPATH,
                                 "//button[. = 'Update']")
    update.click()

    # # 29. Does 'I6' contain '[NONE]'?
    # i6 = driver.find_element(By.XPATH,
    #                          "//div[8]/div[1]/div[2]//i")
    # step_output = i6.text
    # assert step_output and ("" in step_output)

    # 30. Click 'Settings1'
    settings1 = driver.find_element(By.XPATH,
                                    "//span[. = '      Settings']")
    settings1.click()

    # 31. Click 'Logout'
    logout = driver.find_element(By.XPATH,
                                 "//a[. = '       Logout']")
    logout.click()

    # 32. Is 'Login' visible?
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    assert login.is_displayed()
