from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Demo_ Bloomy
    Package: TestProject.Generated.Tests.DemoBloomy
    Test: DeleteWarehouse_TestCase01
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 03/25/2021, 04:14:16
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Demo_ Bloomy",
                              job_name="DeleteWarehouse_TestCase01")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"
    GridValue = "Does 20 of 109 span contain \"20 of 109\" ?"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("rahul.prakash@extrapreneursindia.com")

    # 5. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 6. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 7. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 8. Click 'Stock5'
    stock5 = driver.find_element(By.XPATH,
                                 "//div[. = '\n                Stock\n              ']")
    stock5.click()

    # 9. Does 'Stock2' contain 'Stock'?
    stock2 = driver.find_element(By.XPATH,
                                 "//div[. = 'Stock']")
    step_output = stock2.text
    assert step_output and ("Stock" in step_output)

    # 10. Click 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.click()

    # 11. Type 'ware' in 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.send_keys("ware")

    # 12. Click 'New Warehouse1'
    new_warehouse1 = driver.find_element(By.XPATH,
                                         "//p[. = 'New Warehouse']")
    new_warehouse1.click()

    # 13. Click 'INPUT18'
    input18 = driver.find_element(By.XPATH,
                                  "//div[1]/form/div[1]/div/div[2]/div/input")
    input18.click()

    # 14. Type 'delete waste' in 'INPUT18'
    input18 = driver.find_element(By.XPATH,
                                  "//div[1]/form/div[1]/div/div[2]/div/input")
    input18.send_keys("delete waste")

    # 15. Click 'INPUT21'
    input21 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div[2]/div[1]/div//input")
    input21.click()

    # 16. Click 'Non Stock Item Warehouse1'
    non_stock_item_warehouse1 = driver.find_element(By.XPATH,
                                                    "//strong[. = 'Non Stock Item Warehouse']")
    non_stock_item_warehouse1.click()

    # 17. Click 'INPUT19'
    input19 = driver.find_element(By.XPATH,
                                  "//div[5]/div/div[2]/div[1]/div//input")
    input19.click()

    # 18. Type 'extra' in 'INPUT19'
    input19 = driver.find_element(By.XPATH,
                                  "//div[5]/div/div[2]/div[1]/div//input")
    input19.send_keys("extra")

    # 19. Click 'Extrapreneurs India Pvt Ltd8'
    extrapreneurs_india_pvt_ltd8 = driver.find_element(By.XPATH,
                                                       "//li[. = 'Extrapreneurs India Pvt Ltd']")
    extrapreneurs_india_pvt_ltd8.click()

    # 20. Scroll window by ('0','300')
    driver.execute_script("window.scrollBy(0,300)")

    # 21. Scroll window by ('0','76')
    driver.execute_script("window.scrollBy(0,76)")

    # 22. Click 'INPUT22'
    input22 = driver.find_element(By.XPATH,
                                  "//div[7]//input")
    input22.click()

    # 23. Click 'All Warehouses - VC4'
    all_warehouses_vc4 = driver.find_element(By.XPATH,
                                             "//strong[. = 'All Warehouses - VC']")
    all_warehouses_vc4.click()

    # 24. Does 'New Warehouse 1' contain 'New Warehouse 1'?
    new_warehouse_1 = driver.find_element(By.XPATH,
                                          "//div[. = 'New Warehouse 1']")
    step_output = new_warehouse_1.text
    assert step_output and ("New Warehouse 1" in step_output)

    # 25. Click 'Save5'
    save5 = driver.find_element(By.XPATH,
                                "//button[. = 'Save']")
    save5.click()

    # 26. Scroll window by ('0','-376')
    driver.execute_script("window.scrollBy(0,-376)")

    # 27. Does 'Saved6' contain 'Saved'?
    saved6 = driver.find_element(By.XPATH,
                                 "//div[. = 'Saved']")
    step_output = saved6.text
    assert step_output and ("Saved" in step_output)

    # 28. Click 'Warehouse'
    warehouse = driver.find_element(By.XPATH,
                                    "//li/a[. = 'Warehouse']")
    warehouse.click()

    # 29. Click 'INPUT56'
    input56 = driver.find_element(By.XPATH,
                                  "//div[4]/div[1]/div[1]//input")
    input56.click()

    # 30. Click 'SPAN2'
    span2 = driver.find_element(By.XPATH,
                                "//div[4]/div[1]/div/div/div[2]/div[2]/button/span[1]")
    span2.click()

    # 31. Click 'Delete4'
    delete4 = driver.find_element(By.XPATH,
                                  "//a[. = '\n\t\t\t\tDelete']")
    delete4.click()

    # 32. Click 'Yes1'
    yes1 = driver.find_element(By.XPATH,
                               "//button[. = 'Yes']")
    yes1.click()

    # 33. Does '20 of 109' contain '20 of 109'?
    if float(f'{GridValue}') <= float("Does 20 of 109 span contain \"20 of 109\" ?"):
        _20_of_109 = driver.find_element(By.XPATH,
                                         "//span/span[. = '20 of 109']")
        step_output = _20_of_109.text
        assert step_output and ("20 of 109" in step_output)

    # 34. Click 'Settings'
    settings = driver.find_element(By.XPATH,
                                   "//span[. = '      Settings']")
    settings.click()

    # 35. Click 'Logout'
    logout = driver.find_element(By.XPATH,
                                 "//a[. = '       Logout']")
    logout.click()
