import time

from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Demo_ Bloomy
    Package: TestProject.Generated.Tests.DemoBloomy
    Test: CreateOperation_TestCase01
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 03/31/2021, 03:11:32
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Demo_ Bloomy",
                              job_name="CreateOperation_TestCase01")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("rahul.prakash@extrapreneursindia.com")

    # 5. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 6. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 7. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 8. Click 'Manufacturing'
    manufacturing = driver.find_element(By.XPATH,
                                        "//div[. = '\n                Manufacturing\n              ']")
    manufacturing.click()

    # 9. Does 'Manufacturing1' contain 'Manufacturing'?
    manufacturing1 = driver.find_element(By.XPATH,
                                         "//div[. = 'Manufacturing']")
    step_output = manufacturing1.text
    assert step_output and ("Manufacturing" in step_output)

    # 10. Click 'Operation'
    operation = driver.find_element(By.XPATH,
                                    "//a[. = 'Operation']")
    operation.click()

    # 11. Does 'Operation1' contain 'Operation'?
    operation1 = driver.find_element(By.XPATH,
                                     "//div[. = 'Operation']")
    step_output = operation1.text
    assert step_output and ("Operation" in step_output)
    time.sleep(2)

    # 12. Click 'New'
    new = driver.find_element(By.XPATH,
                              "//span[. = 'New']")
    new.click()

    # 13. Click 'Edit in full page'
    edit_in_full_page = driver.find_element(By.XPATH,
                                            "//button[. = 'Edit in full page']")
    edit_in_full_page.click()

    # 14. Click 'INPUT54'
    input54 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div/form/div[1]//input")
    input54.click()

    # 15. Type 'Tester01' in 'INPUT54'
    input54 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div/form/div[1]//input")
    input54.send_keys("Tester01")

    # 16. Click 'TEXTAREA1'
    textarea1 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea1.click()

    # 17. Type 'Hiii' in 'TEXTAREA1'
    textarea1 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea1.send_keys("Hiii")

    # 18. Does 'New Operation 1' contain 'New Operation 1'?
    new_operation_1 = driver.find_element(By.XPATH,
                                          "//div[. = 'New Operation 1']")
    step_output = new_operation_1.text
    assert step_output and ("New Operation 1" in step_output)
    time.sleep(2)

    # 19. Click 'Save'
    save = driver.find_element(By.XPATH,
                               "//span[. = 'Save']")
    save.click()

    # 20. Does 'Saved10' contain 'Saved'?
    saved10 = driver.find_element(By.XPATH,
                                  "//div[. = 'Saved']")
    step_output = saved10.text
    assert step_output and ("Saved" in step_output)

    # 21. Click 'Operation2'
    operation2 = driver.find_element(By.XPATH,
                                     "//li/a[. = 'Operation']")
    operation2.click()

    # 22. Click 'Settings'
    settings = driver.find_element(By.XPATH,
                                   "//span[. = '      Settings']")
    settings.click()

    # 23. Click 'Logout'
    logout = driver.find_element(By.XPATH,
                                 "//a[. = '       Logout']")
    logout.click()
