from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Bloomy_Core
    Package: TestProject.Generated.Tests.BloomyCore
    Test: E2EWF_Purchase_Purchase Order02
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 05/19/2021, 11:28:57
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Bloomy_Core",
                              job_name="E2EWF_Purchase_Purchase Order02")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """1. Go to the Purchase Order list, click on New.

    2. Select the Supplier, required by date..3. In the items table, select the item by code, you can change the required by date for each item..
    """
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("rahul.prakash@extrapreneursindia.com")

    # 5. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 6. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 7. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 8. Click 'Purchasing'
    purchasing = driver.find_element(By.XPATH,
                                     "//div[. = '\n                Purchasing\n              ']")
    purchasing.click()

    # 9. Does 'Purchasing1' contain 'Purchasing'?
    purchasing1 = driver.find_element(By.XPATH,
                                      "//div[. = 'Purchasing']")
    step_output = purchasing1.text
    assert step_output and ("Purchasing" in step_output)

    # 10. Click 'Purchase Order'
    purchase_order = driver.find_element(By.XPATH,
                                         "//div/a[. = 'Purchase Order']")
    purchase_order.click()

    # 11. Does 'Purchase Order1' contain 'Purchase Order'?
    purchase_order1 = driver.find_element(By.XPATH,
                                          "//div[. = 'Purchase Order']")
    step_output = purchase_order1.text
    assert step_output and ("Purchase Order" in step_output)

    # 12. Click 'New'
    new = driver.find_element(By.XPATH,
                              "//span[. = 'New']")
    new.click()

    # 13. Click 'INPUT21'
    input21 = driver.find_element(By.XPATH,
                                  "//div[3]/div/div[1]/form/div[3]//input")
    input21.click()

    # 14. Click 'P49'
    p49 = driver.find_element(By.XPATH,
                              "//li[9]//p")
    p49.click()

    # 15. Click 'License1'
    license1 = driver.find_element(By.XPATH,
                                   "//label[. = 'License']")
    license1.click()

    # 16. Click 'INPUT28'
    input28 = driver.find_element(By.XPATH,
                                  "//div[3]/div/div[2]/form/div[2]//input")
    input28.click()

    # 17. Click 'svg7'
    svg7 = driver.find_element(By.XPATH,
                               "//div[2]/nav/div[3]/*")
    svg7.click()

    # 18. Click 'svg7'
    svg7 = driver.find_element(By.XPATH,
                               "//div[2]/nav/div[3]/*")
    svg7.click()

    # 19. Click 'svg7'
    svg7 = driver.find_element(By.XPATH,
                               "//div[2]/nav/div[3]/*")
    svg7.click()

    # 20. Click '295'
    _295 = driver.find_element(By.XPATH,
                               "//div[2]/div//div[33][. = '29']")
    _295.click()

    # 21. Click 'INPUT41'
    input41 = driver.find_element(By.XPATH,
                                  "//div[1]/form/div[6]//input")
    input41.click()

    # 22. Type 'vap' in 'INPUT41'
    input41 = driver.find_element(By.XPATH,
                                  "//div[1]/form/div[6]//input")
    input41.send_keys("vap")

    # 23. Click 'VapeCo15'
    vapeco15 = driver.find_element(By.XPATH,
                                   "//li[. = 'VapeCo']")
    vapeco15.click()

    # 24. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 25. Scroll window by ('0','200')
    driver.execute_script("window.scrollBy(0,200)")

    # 26. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 27. Does 'New Purchase Order 13' contain 'New Purchase Order 1'?
    new_purchase_order_13 = driver.find_element(By.XPATH,
                                                "//div[. = 'New Purchase Order 1']")
    step_output = new_purchase_order_13.text
    assert step_output and ("New Purchase Order 1" in step_output)

    # 28. Click 'DIV27'
    div27 = driver.find_element(By.XPATH,
                                "//div[2]/div/div[2]/div[2]/div[1]/div/div/div[2]")
    div27.click()

    # 29. Click 'Finished Oil, Dry Goods, Extracted Ja...1'
    finished_oil_dry_goods_extracted_ja_1 = driver.find_element(By.XPATH,
                                                                "//span[. = 'Finished Oil, Dry Goods, Extracted Jack Herer Cannabis Oil']")
    finished_oil_dry_goods_extracted_ja_1.click()

    # 30. Scroll window by ('0','-58')
    driver.execute_script("window.scrollBy(0,-58)")

    # 31. Click 'Save'
    save = driver.find_element(By.XPATH,
                               "//span[. = 'Save']")
    save.click()

    # 32. Scroll window by ('0','-342')
    driver.execute_script("window.scrollBy(0,-342)")

    # 33. Does 'Saved9' contain 'Saved'?
    saved9 = driver.find_element(By.XPATH,
                                 "//div[. = 'Saved']")
    step_output = saved9.text
    assert step_output and ("Saved" in step_output)

    # 34. Does 'Draft' contain 'Draft'?
    draft = driver.find_element(By.XPATH,
                                "//span/span[. = 'Draft']")
    step_output = draft.text
    assert step_output and ("Draft" in step_output)

    # 35. Click 'Submit'
    submit = driver.find_element(By.XPATH,
                                 "//button/span[. = 'Submit']")
    submit.click()

    # 36. Click 'Yes1'
    yes1 = driver.find_element(By.XPATH,
                               "//button[. = 'Yes']")
    yes1.click()

    # 37. Does 'DIV44' contain '[NONE]'?
    div44 = driver.find_element(By.XPATH,
                                "//div[5]/div/div[3]")
    step_output = div44.text
    assert step_output and ("" in step_output)

    # 38. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[1]/div[1]/button/i")
    i5.click()

    # 39. Does 'New Purchase Receipt 14' contain 'New Purchase Receipt 1'?
    new_purchase_receipt_14 = driver.find_element(By.XPATH,
                                                  "//div[. = 'New Purchase Receipt 1']")
    step_output = new_purchase_receipt_14.text
    assert step_output and ("New Purchase Receipt 1" in step_output)

    # 40. Click 'Save1'
    save1 = driver.find_element(By.XPATH,
                                "//span[. = 'Save']")
    save1.click()

    # 41. Does 'Saved16' contain 'Saved'?
    saved16 = driver.find_element(By.XPATH,
                                  "//div[4]/div[. = 'Saved']")
    step_output = saved16.text
    assert step_output and ("Saved" in step_output)

    # 42. Click 'Submit2'
    submit2 = driver.find_element(By.XPATH,
                                  "//div[5]//span[. = 'Submit']")
    submit2.click()

    # 43. Click 'Yes4'
    yes4 = driver.find_element(By.XPATH,
                               "//div[2]/div/div//button[. = 'Yes']")
    yes4.click()

    # 44. Does 'Saved20' contain 'Saved'?
    saved20 = driver.find_element(By.XPATH,
                                  "//div[5]/div[. = 'Saved']")
    step_output = saved20.text
    assert step_output and ("Saved" in step_output)

    # 45. Does 'Purchase Receipt has been submitted s...8' contain 'Purchase Receipt has been submitted successfully'?
    purchase_receipt_has_been_submitted_s_8 = driver.find_element(By.XPATH,
                                                                  "//div[. = 'Purchase Receipt has been submitted successfully']")
    step_output = purchase_receipt_has_been_submitted_s_8.text
    assert step_output and (
        "Purchase Receipt has been submitted successfully" in step_output)

    # 46. Click 'I13'
    i13 = driver.find_element(By.XPATH,
                              "//div[5]/div[2]/div[2]/div/div[3]/div[2]/div[1]/div[3]/div/div/div[2]/div[1]/div[2]/div/div[5]/div/div/div[1]/div[1]/div[1]//i")
    i13.click()

    # 47. Does 'New Purchase Invoice 14' contain 'New Purchase Invoice 1'?
    new_purchase_invoice_14 = driver.find_element(By.XPATH,
                                                  "//div[. = 'New Purchase Invoice 1']")
    step_output = new_purchase_invoice_14.text
    assert step_output and ("New Purchase Invoice 1" in step_output)

    # 48. Click 'SELECT18'
    select18 = driver.find_element(By.XPATH,
                                   "//div[2]/div/div[1]/form//select")
    select18.click()

    # 49. Select the 'ACC-PINV-.YYYY.-' option in 'SELECT18'
    select18 = driver.find_element(By.XPATH,
                                   "//div[2]/div/div[1]/form//select")
    Select(select18).select_by_value("ACC-PINV-.YYYY.-")

    # 50. Click 'SELECT18'
    select18 = driver.find_element(By.XPATH,
                                   "//div[2]/div/div[1]/form//select")
    select18.click()

    # 51. Click 'Save18'
    save18 = driver.find_element(By.XPATH,
                                 "//button[. = 'Save']")
    save18.click()

    # 52. Does 'Saved44' contain 'Saved'?
    saved44 = driver.find_element(By.XPATH,
                                  "//div[7]/div[. = 'Saved']")
    step_output = saved44.text
    assert step_output and ("Saved" in step_output)

    # 53. Click 'Submit13'
    submit13 = driver.find_element(By.XPATH,
                                   "//div[6]//span[. = 'Submit']")
    submit13.click()

    # 54. Click 'Yes2'
    yes2 = driver.find_element(By.XPATH,
                               "//div[2]/div/div//button[. = 'Yes']")
    yes2.click()

    # 55. Does 'Purchase Invoice has been submitted s...3' contain 'Purchase Invoice has been submitted successfully'?
    purchase_invoice_has_been_submitted_s_3 = driver.find_element(By.XPATH,
                                                                  "//div[. = 'Purchase Invoice has been submitted successfully']")
    step_output = purchase_invoice_has_been_submitted_s_3.text
    assert step_output and (
        "Purchase Invoice has been submitted successfully" in step_output)

    # 56. Click 'I9'
    i9 = driver.find_element(By.XPATH,
                             "//div[6]/div[2]/div[2]/div/div[3]/div[2]/div[1]/div[3]/div/div/div[2]/div[1]/div[2]/div/div[5]/div/div/div[1]/div[1]/div[1]//i")
    i9.click()

    # 57. Click 'INPUT55'
    input55 = driver.find_element(By.XPATH,
                                  "//div[3]/div[2]/div[2]/form/div[3]//input")
    input55.click()

    # 58. Type 'ca' in 'INPUT55'
    input55 = driver.find_element(By.XPATH,
                                  "//div[3]/div[2]/div[2]/form/div[3]//input")
    input55.send_keys("ca")

    # 59. Click 'Cash12'
    cash12 = driver.find_element(By.XPATH,
                                 "//p[. = 'Cash']")
    cash12.click()

    # 60. Does 'Payment Entry2' contain 'Payment Entry'?
    payment_entry2 = driver.find_element(By.XPATH,
                                         "//li/a[. = 'Payment Entry']")
    step_output = payment_entry2.text
    assert step_output and ("Payment Entry" in step_output)

    # 61. Click 'Save29'
    save29 = driver.find_element(By.XPATH,
                                 "//button[. = 'Save']")
    save29.click()

    # 62. Does 'Saved25' contain 'Saved'?
    saved25 = driver.find_element(By.XPATH,
                                  "//div[10]/div[. = 'Saved']")
    step_output = saved25.text
    assert step_output and ("Saved" in step_output)

    # 63. Does 'Draft4' contain 'Draft'?
    draft4 = driver.find_element(By.XPATH,
                                 "//span/span[. = 'Draft']")
    step_output = draft4.text
    assert step_output and ("Draft" in step_output)

    # 64. Click 'Submit3'
    submit3 = driver.find_element(By.XPATH,
                                  "//div[7]//span[. = 'Submit']")
    submit3.click()

    # 65. Click 'Yes2'
    yes2 = driver.find_element(By.XPATH,
                               "//div[2]/div/div//button[. = 'Yes']")
    yes2.click()

    # 66. Does 'Saved45' contain 'Saved'?
    saved45 = driver.find_element(By.XPATH,
                                  "//div[11]/div[. = 'Saved']")
    step_output = saved45.text
    assert step_output and ("Saved" in step_output)

    # 67. Does 'Submitted6' contain 'Submitted'?
    submitted6 = driver.find_element(By.XPATH,
                                     "//span/span[. = 'Submitted']")
    step_output = submitted6.text
    assert step_output and ("Submitted" in step_output)

    # 68. Click 'Settings'
    settings = driver.find_element(By.XPATH,
                                   "//span[. = '      Settings']")
    settings.click()

    # 69. Click 'Logout'
    logout = driver.find_element(By.XPATH,
                                 "//a[. = '       Logout']")
    logout.click()
