import time

from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Demo_ Bloomy
    Package: TestProject.Generated.Tests.DemoBloomy
    Test: CreateSupplier_TestCase01
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 03/10/2021, 06:58:00
"""


@pytest.fixture()
def driver():
    driver = webdriver.Firefox(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                               project_name="Demo_ Bloomy",
                               job_name="CreateSupplier_TestCase01")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("rahul.prakash@extrapreneursindia.com")

    # 5. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 6. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 7. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 8. Click 'Purchasing'
    purchasing = driver.find_element(By.XPATH,
                                     "//div[. = '\n                Purchasing\n              ']")
    purchasing.click()

    # 9. Click 'Supplier1'
    supplier1 = driver.find_element(By.XPATH,
                                    "//div/a[. = 'Supplier']")
    supplier1.click()

    # 10. Does 'Supplier3' contain 'Supplier'?
    supplier3 = driver.find_element(By.XPATH,
                                    "//div[. = 'Supplier']")
    step_output = supplier3.text
    assert step_output and ("Supplier" in step_output)

    # 11. Click 'New5'
    new5 = driver.find_element(By.XPATH,
                               "//button[. = 'New']")
    new5.click()
    time.sleep(3)

    # 12. Click 'INPUT34'
    input34 = driver.find_element(By.XPATH,
                                  "//form/div[1]/div/div//input")
    input34.click()

    # 13. Type 'Tester Team1' in 'INPUT34'
    input34 = driver.find_element(By.XPATH,
                                  "//form/div[1]/div/div//input")
    input34.send_keys("Tester Team1")

    # 14. Click 'INPUT35'
    input35 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div[2]/div[1]/div/div/input")
    input35.click()

    # 15. Click 'Raw Material1'
    raw_material1 = driver.find_element(By.XPATH,
                                        "//strong[. = 'Raw Material']")
    raw_material1.click()

    # 16. Click 'SELECT7'
    select7 = driver.find_element(By.XPATH,
                                  "//select")
    select7.click()

    # 17. Click 'SELECT7'
    select7 = driver.find_element(By.XPATH,
                                  "//select")
    select7.click()

    # 18. Click 'Edit in full page'
    edit_in_full_page = driver.find_element(By.XPATH,
                                            "//button[. = 'Edit in full page']")
    edit_in_full_page.click()

    # 19. Scroll window by ('0','300')
    driver.execute_script("window.scrollBy(0,300)")

    # 20. Scroll window by ('0','264')
    driver.execute_script("window.scrollBy(0,264)")

    # 21. Click 'Save'
    save = driver.find_element(By.XPATH,
                               "//span[. = 'Save']")
    save.click()

    # 22. Scroll window by ('0','-564')
    driver.execute_script("window.scrollBy(0,-564)")

    # 23. Does 'Saved6' contain 'Saved'?
    saved6 = driver.find_element(By.XPATH,
                                 "//div[. = 'Saved']")
    step_output = saved6.text
    assert step_output and ("Saved" in step_output)

    # 24. Click 'Supplier4'
    supplier4 = driver.find_element(By.XPATH,
                                    "//li[2]/a[. = 'Supplier']")
    supplier4.click()
