from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Demo_ Bloomy
    Package: TestProject.Generated.Tests.DemoBloomy
    Test: DeleteJobCard_TestCase
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 03/16/2021, 11:48:02
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Demo_ Bloomy",
                              job_name="DeleteJobCard_TestCase")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("rahul.prakash@extrapreneursindia.com")

    # 5. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 6. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 7. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 8. Click 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.click()

    # 9. Type 'item' in 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.send_keys("item")

    # 10. Click 'New Item3'
    new_item3 = driver.find_element(By.XPATH,
                                    "//span[. = 'New Item']")
    new_item3.click()

    # 11. Click 'INPUT22'
    input22 = driver.find_element(By.XPATH,
                                  "//div[3]/div/div[2]//input")
    input22.click()

    # 12. Type 'Item Delete' in 'INPUT22'
    input22 = driver.find_element(By.XPATH,
                                  "//div[3]/div/div[2]//input")
    input22.send_keys("Item Delete")

    # 13. Click 'INPUT23'
    input23 = driver.find_element(By.XPATH,
                                  "//div[4]/div/div[2]//input")
    input23.click()

    # 14. Type 'Item delete' in 'INPUT23'
    input23 = driver.find_element(By.XPATH,
                                  "//div[4]/div/div[2]//input")
    input23.send_keys("Item delete")

    # 15. Click 'INPUT23'
    input23 = driver.find_element(By.XPATH,
                                  "//div[4]/div/div[2]//input")
    input23.click()

    # 16. Type 'Item Delete' in 'INPUT23'
    input23 = driver.find_element(By.XPATH,
                                  "//div[4]/div/div[2]//input")
    input23.send_keys("Item Delete")

    # 17. Click 'INPUT24'
    input24 = driver.find_element(By.XPATH,
                                  "//div[5]//input")
    input24.click()

    # 18. Click 'All Item Groups1'
    all_item_groups1 = driver.find_element(By.XPATH,
                                           "//strong[. = 'All Item Groups']")
    all_item_groups1.click()

    # 19. Click 'Save4'
    save4 = driver.find_element(By.XPATH,
                                "//button[. = 'Save']")
    save4.click()

    # 20. Does 'Item Delete' contain 'Item Delete'?
    item_delete = driver.find_element(By.XPATH,
                                      "//h1//div[. = 'Item Delete']")
    step_output = item_delete.text
    assert step_output and ("Item Delete" in step_output)

    # 21. Click 'HTML'
    html = driver.find_element(By.XPATH,
                               "/html")
    html.click()

    # 22. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[1]/div[1]/div[1]/button/i")
    i5.click()

    # 23. Click 'INPUT26'
    input26 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div[1]/form/div[4]//input")
    input26.click()

    # 24. Type 'vap' in 'INPUT26'
    input26 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div[1]/form/div[4]//input")
    input26.send_keys("vap")

    # 25. Click 'VapeCo3'
    vapeco3 = driver.find_element(By.XPATH,
                                  "//p[. = 'VapeCo']")
    vapeco3.click()

    # 26. Scroll window by ('0','400')
    driver.execute_script("window.scrollBy(0,400)")

    # 27. Scroll window by ('0','200')
    driver.execute_script("window.scrollBy(0,200)")

    # 28. Click 'Add Row'
    add_row = driver.find_element(By.XPATH,
                                  "//div[6]//button[. = '\n\t\t\t\t\t\t\tAdd Row']")
    add_row.click()

    # 29. Click 'DIV14'
    div14 = driver.find_element(By.XPATH,
                                "//div[3]/div/div[2]/div[2]/div[1]/div/div/div[2]")
    div14.click()

    # 30. Click 'VC-RM-FO-00011'
    vc_rm_fo_00011 = driver.find_element(By.XPATH,
                                         "//strong[. = 'VC-RM-FO-0001']")
    vc_rm_fo_00011.click()

    # 31. Does 'New BOM 11' contain 'New BOM 1'?
    new_bom_11 = driver.find_element(By.XPATH,
                                     "//div[. = 'New BOM 1']")
    step_output = new_bom_11.text
    assert step_output and ("New BOM 1" in step_output)

    # 32. Click 'Save10'
    save10 = driver.find_element(By.XPATH,
                                 "//div[3]//span[. = 'Save']")
    save10.click()

    # 33. Scroll window by ('0','-600')
    driver.execute_script("window.scrollBy(0,-600)")

    # 34. Does 'Saved16' contain 'Saved'?
    saved16 = driver.find_element(By.XPATH,
                                  "//div[. = 'Saved']")
    step_output = saved16.text
    assert step_output and ("Saved" in step_output)

    # 35. Click 'Submit2'
    submit2 = driver.find_element(By.XPATH,
                                  "//span[. = 'Submit']")
    submit2.click()

    # 36. Click 'Yes2'
    yes2 = driver.find_element(By.XPATH,
                               "//button[. = 'Yes']")
    yes2.click()

    # 37. Does 'Saved12' contain 'Saved'?
    saved12 = driver.find_element(By.XPATH,
                                  "//div[3]/div[. = 'Saved']")
    step_output = saved12.text
    assert step_output and ("Saved" in step_output)

    # 38. Click 'Create3'
    create3 = driver.find_element(By.XPATH,
                                  "//button[. = '\t\t\t\tCreate ']")
    create3.click()

    # 39. Click 'Work Order5'
    work_order5 = driver.find_element(By.XPATH,
                                      "//div[2]/div[1]/div[1]/div/ul//a[. = 'Work Order']")
    work_order5.click()

    # 40. Click 'Create'
    create = driver.find_element(By.XPATH,
                                 "//button[. = 'Create']")
    create.click()

    # 41. Click 'Save12'
    save12 = driver.find_element(By.XPATH,
                                 "//div[4]//button[2][. = 'Save']")
    save12.click()

    # 42. Does 'Saved25' contain 'Saved'?
    saved25 = driver.find_element(By.XPATH,
                                  "//div[4]/div[. = 'Saved']")
    step_output = saved25.text
    assert step_output and ("Saved" in step_output)

    # 43. Does 'Draft' contain 'Draft'?
    draft = driver.find_element(By.XPATH,
                                "//span/span[. = 'Draft']")
    step_output = draft.text
    assert step_output and ("Draft" in step_output)

    # 44. Click 'Submit4'
    submit4 = driver.find_element(By.XPATH,
                                  "//div[4]//span[. = 'Submit']")
    submit4.click()

    # 45. Click 'Yes3'
    yes3 = driver.find_element(By.XPATH,
                               "//div[2]/div/div//button[. = 'Yes']")
    yes3.click()

    # 46. Does 'Saved26' contain 'Saved'?
    saved26 = driver.find_element(By.XPATH,
                                  "//div[5]/div[. = 'Saved']")
    step_output = saved26.text
    assert step_output and ("Saved" in step_output)

    # 47. Does 'Not Started' contain 'Not Started'?
    not_started = driver.find_element(By.XPATH,
                                      "//span/span[. = 'Not Started']")
    step_output = not_started.text
    assert step_output and ("Not Started" in step_output)

    # 48. Click 'Job Card'
    job_card = driver.find_element(By.XPATH,
                                   "//div[2]/a[. = 'Job Card']")
    job_card.click()

    # 49. Does 'Job Card1' contain 'Job Card'?
    job_card1 = driver.find_element(By.XPATH,
                                    "//div[. = 'Job Card']")
    step_output = job_card1.text
    assert step_output and ("Job Card" in step_output)

    # 50. Click 'New5'
    new5 = driver.find_element(By.XPATH,
                               "//span[. = 'New']")
    new5.click()

    # 51. Click 'INPUT36'
    input36 = driver.find_element(By.XPATH,
                                  "//div[2]/div[1]/div[1]/div[2]/div/div/div/form/div[3]/div/div[2]/div[1]/div//input")
    input36.click()

    # 52. Click 'Mixing Station1'
    mixing_station1 = driver.find_element(By.XPATH,
                                          "//li[. = 'Mixing Station']")
    mixing_station1.click()

    # 53. Click 'INPUT37'
    input37 = driver.find_element(By.XPATH,
                                  "//div[2]/div[1]/div[1]/div[2]/div/div/div/form/div[4]/div/div[2]/div[1]/div//input")
    input37.click()

    # 54. Click 'EPI-Wakad'
    epi_wakad = driver.find_element(By.XPATH,
                                    "//li[1]//p[. = 'EPI-Wakad']")
    epi_wakad.click()

    # 55. Click 'INPUT38'
    input38 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div[2]/div[1]/div[1]/div[2]/div/div/div/form/div[5]//input")
    input38.click()

    # 56. Type 'va' in 'INPUT38'
    input38 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div[2]/div[1]/div[1]/div[2]/div/div/div/form/div[5]//input")
    input38.send_keys("va")

    # 57. Click 'VapeCo12'
    vapeco12 = driver.find_element(By.XPATH,
                                   "//div[5]//p[. = 'VapeCo']")
    vapeco12.click()

    # 58. Click 'INPUT39'
    input39 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div[2]/div[1]/div[1]/div[2]/div/div/div/form/div[6]//input")
    input39.click()

    # 59. Click 'Non Stock Accounts Warehouse - BTPL'
    non_stock_accounts_warehouse_btpl = driver.find_element(By.XPATH,
                                                            "//strong[. = 'Non Stock Accounts Warehouse - BTPL']")
    non_stock_accounts_warehouse_btpl.click()

    # 60. Click 'Save13'
    save13 = driver.find_element(By.XPATH,
                                 "//div[2]/div/div//button[3][. = 'Save']")
    save13.click()

    # 61. Click 'Submit6'
    submit6 = driver.find_element(By.XPATH,
                                  "//button[3][. = 'Submit']")
    submit6.click()

    # 62. Click 'PO-JOB00365'
    po_job00365 = driver.find_element(By.XPATH,
                                      "//a[. = 'PO-JOB00365']")
    po_job00365.click()

    # 63. Scroll window by ('0','400')
    driver.execute_script("window.scrollBy(0,400)")

    # 64. Scroll window by ('0','500')
    driver.execute_script("window.scrollBy(0,500)")

    # 65. Click 'Add Row2'
    add_row2 = driver.find_element(By.XPATH,
                                   "//div[4]/div[2]/div/form//button[. = '\n\t\t\t\t\t\t\tAdd Row']")
    add_row2.click()

    # 66. Click 'DIV17'
    div17 = driver.find_element(By.XPATH,
                                "//div[4]/div[2]/div/form/div/div/div[2]/div[2]/div[1]/div/div/div[2]")
    div17.click()

    # 67. Click '29'
    _29 = driver.find_element(By.XPATH,
                              "//div[5]//div[. = '29']")
    _29.click()

    # 68. Click 'To Time'
    to_time = driver.find_element(By.XPATH,
                                  "//input[@placeholder = 'To Time']")
    to_time.click()

    # 69. Click '304'
    _304 = driver.find_element(By.XPATH,
                               "//div[6]/div[1]//div[31][. = '30']")
    _304.click()

    # 70. Click 'Save9'
    save9 = driver.find_element(By.XPATH,
                                "//div[6]//span[. = 'Save']")
    save9.click()

    # 71. Scroll window by ('0','-900')
    driver.execute_script("window.scrollBy(0,-900)")

    # 72. Does 'Saved23' contain 'Saved'?
    saved23 = driver.find_element(By.XPATH,
                                  "//div[6]/div[. = 'Saved']")
    step_output = saved23.text
    assert step_output and ("Saved" in step_output)

    # 73. Does 'EPI-Wakad2' contain 'EPI-Wakad'?
    epi_wakad2 = driver.find_element(By.XPATH,
                                     "//div[. = 'EPI-Wakad']")
    step_output = epi_wakad2.text
    assert step_output and ("EPI-Wakad" in step_output)

    # 74. Click 'Job Card4'
    job_card4 = driver.find_element(By.XPATH,
                                    "//li/a[. = 'Job Card']")
    job_card4.click()

    # 75. Click 'INPUT46'
    input46 = driver.find_element(By.XPATH,
                                  "//div[2]/div[2]/div[1]/div[1]/div/input")
    input46.click()

    # 76. Click 'SPAN2'
    span2 = driver.find_element(By.XPATH,
                                "//div[5]/div[1]/div/div/div[2]/div[2]/button/span[1]")
    span2.click()

    # 77. Click 'Delete'
    delete = driver.find_element(By.XPATH,
                                 "//a[. = '\n\t\t\t\tDelete']")
    delete.click()

    # 78. Click 'Yes4'
    yes4 = driver.find_element(By.XPATH,
                               "//div[2]/div/div//button[. = 'Yes']")
    yes4.click()

    # 79. Click 'Settings'
    settings = driver.find_element(By.XPATH,
                                   "//span[. = '      Settings']")
    settings.click()

    # 80. Click 'Logout'
    logout = driver.find_element(By.XPATH,
                                 "//a[. = '       Logout']")
    logout.click()
