import time

from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Demo_ Bloomy
    Package: TestProject.Generated.Tests.DemoBloomy
    Test: DeleteTimesheet_TestCase02
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 03/15/2021, 08:04:01
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Demo_ Bloomy",
                              job_name="DeleteTimesheet_TestCase02")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("rahul.prakash@extrapreneursindia.com")

    # 5. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 6. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 7. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 8. Click 'Manufacturing'
    manufacturing = driver.find_element(By.XPATH,
                                        "//div[. = '\n                Manufacturing\n              ']")
    manufacturing.click()

    # 9. Does 'Manufacturing1' contain 'Manufacturing'?
    manufacturing1 = driver.find_element(By.XPATH,
                                         "//div[. = 'Manufacturing']")
    step_output = manufacturing1.text
    assert step_output and ("Manufacturing" in step_output)

    # 10. Click 'Timesheet'
    timesheet = driver.find_element(By.XPATH,
                                    "//div/a[. = 'Timesheet']")
    timesheet.click()

    # 11. Does 'Timesheet1' contain 'Timesheet'?
    timesheet1 = driver.find_element(By.XPATH,
                                     "//div[. = 'Timesheet']")
    step_output = timesheet1.text
    assert step_output and ("Timesheet" in step_output)
    time.sleep(2)

    # 12. Click 'New'
    new = driver.find_element(By.XPATH,
                              "//span[. = 'New']")
    new.click()

    # 13. Does 'New Timesheet 1' contain 'New Timesheet 1'?
    new_timesheet_1 = driver.find_element(By.XPATH,
                                          "//div[. = 'New Timesheet 1']")
    step_output = new_timesheet_1.text
    assert step_output and ("New Timesheet 1" in step_output)

    # 14. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//div[4]/div/div[2]/div[1]/div/div/input")
    input1.click()

    # 15. Type 'extra' in 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//div[4]/div/div[2]/div[1]/div/div/input")
    input1.send_keys("extra")

    # 16. Click 'Extrapreneurs India Pvt Ltd3'
    extrapreneurs_india_pvt_ltd3 = driver.find_element(By.XPATH,
                                                       "//strong[. = 'Extrapreneurs India Pvt Ltd']")
    extrapreneurs_india_pvt_ltd3.click()

    # 17. Click 'INPUT21'
    input21 = driver.find_element(By.XPATH,
                                  "//div[2]/div[1]/form//input")
    input21.click()

    # 18. Click 'HR-EMP-00066'
    hr_emp_00066 = driver.find_element(By.XPATH,
                                       "//strong[. = 'HR-EMP-00066']")
    hr_emp_00066.click()

    # 19. Scroll window by ('0','200')
    driver.execute_script("window.scrollBy(0,200)")

    # 20. Click 'DIV6'
    div6 = driver.find_element(By.XPATH,
                               "//form/div/div/div[2]/div[2]/div[1]/div/div/div[2]")
    div6.click()

    # 21. Type 'epi' in 'Activity Type'
    activity_type = driver.find_element(By.XPATH,
                                        "//input[@placeholder = 'Activity Type']")
    activity_type.send_keys("epi")

    # 22. Click 'EPI-Bug reporting'
    epi_bug_reporting = driver.find_element(By.XPATH,
                                            "//li[. = 'EPI-Bug reporting']")
    epi_bug_reporting.click()

    # 23. Click 'From Time'
    from_time = driver.find_element(By.XPATH,
                                    "//input[@placeholder = 'From Time']")
    from_time.click()

    # 24. Click '311'
    _311 = driver.find_element(By.XPATH,
                               "//div[. = '31']")
    _311.click()

    # 25. Click 'Hrs'
    hrs = driver.find_element(By.XPATH,
                              "//input[@placeholder = 'Hrs']")
    hrs.click()

    # 26. Type '7.00' in 'Hrs'
    hrs = driver.find_element(By.XPATH,
                              "//input[@placeholder = 'Hrs']")
    hrs.send_keys("7.00")

    # 27. Click 'Project'
    project = driver.find_element(By.XPATH,
                                  "//input[@placeholder = 'Project']")
    project.click()

    # 28. Click 'EPI- Test Project'
    epi_test_project = driver.find_element(By.XPATH,
                                           "//strong[. = 'EPI- Test Project']")
    epi_test_project.click()

    # 29. Click 'Save'
    save = driver.find_element(By.XPATH,
                               "//span[. = 'Save']")
    save.click()

    # 30. Scroll window by ('0','-200')
    driver.execute_script("window.scrollBy(0,-200)")

    # 31. Does 'Saved10' contain 'Saved'?
    saved10 = driver.find_element(By.XPATH,
                                  "//div[. = 'Saved']")
    step_output = saved10.text
    assert step_output and ("Saved" in step_output)

    # 32. Click 'Timesheet3'
    timesheet3 = driver.find_element(By.XPATH,
                                     "//li[2]/a[. = 'Timesheet']")
    timesheet3.click()

    # 33. Click 'INPUT3'
    input3 = driver.find_element(By.XPATH,
                                 "//div[2]/div[2]/div[1]/div[1]/div/input")
    input3.click()

    # 34. Click 'SPAN'
    span = driver.find_element(By.XPATH,
                               "//div[3]/div[1]/div/div/div[2]/div[2]/button/span[1]")
    span.click()

    # 35. Click 'Delete1'
    delete1 = driver.find_element(By.XPATH,
                                  "//div[2]/ul//span[. = 'Delete']")
    delete1.click()

    # 36. Click 'Yes'
    yes = driver.find_element(By.XPATH,
                              "//button[. = 'Yes']")
    yes.click()

    # 37. Click 'Settings'
    settings = driver.find_element(By.XPATH,
                                   "//span[. = '      Settings']")
    settings.click()

    # 38. Click 'Logout'
    logout = driver.find_element(By.XPATH,
                                 "//a[. = '       Logout']")
    logout.click()
