import time

from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Bloomy_Core
    Package: TestProject.Generated.Tests.BloomyCore
    Test: UpdateItemTestCase_01
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 05/26/2021, 07:17:09
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Bloomy_Core",
                              job_name="UpdateItemTestCase_01")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Generated By : Rahul."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Is 'Login' visible?
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    assert login.is_displayed()

    # 3. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 4. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 5. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("testautomationuser@bloomstack.com")

    # 6. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 7. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 8. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 9. Click 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.click()

    # 10. Type 'item' in 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.send_keys("item")

    # 11. Click 'Item List2'
    item_list2 = driver.find_element(By.XPATH,
                                     "//p[. = 'Item List']")
    item_list2.click()

    # 12. Does 'Item5' contain 'Item'?
    item5 = driver.find_element(By.XPATH,
                                "//div[. = 'Item']")
    step_output = item5.text
    assert step_output and ("Item" in step_output)
    time.sleep(2)

    # 13. Click 'N'
    n = driver.find_element(By.XPATH,
                            "//span[. = 'N']")
    n.click()

    # 14. Click 'INPUT39'
    input39 = driver.find_element(By.XPATH,
                                  "//div[3]/div/div[2]/div/input")
    input39.click()

    # 15. Type 'Test code' in 'INPUT39'
    input39 = driver.find_element(By.XPATH,
                                  "//div[3]/div/div[2]/div/input")
    input39.send_keys("Test code")

    # 16. Click 'INPUT40'
    input40 = driver.find_element(By.XPATH,
                                  "//div[4]/div/div[2]//input")
    input40.click()

    # 17. Type 'Test code' in 'INPUT40'
    input40 = driver.find_element(By.XPATH,
                                  "//div[4]/div/div[2]//input")
    input40.send_keys("Test code")

    # 18. Is 'New Item1' visible?
    new_item1 = driver.find_element(By.XPATH,
                                    "//h4[. = 'New Item']")
    assert new_item1.is_displayed()

    # 19. Click 'Save'
    save = driver.find_element(By.XPATH,
                               "//button[. = 'Save']")
    save.click()
    time.sleep(2)

    # 20. Click 'INPUT129'
    input129 = driver.find_element(By.XPATH,
                                   "(//input[@class='level-item list-row-checkbox hidden-xs'])[1]")
    driver.execute_script( "arguments[0].click();", input129 )

    # 21. Click 'Actions3'
    actions3 = driver.find_element(By.XPATH,
                                   "//button[. = '               Actions                            ']")
    actions3.click()

    # 22. Click 'Edit1'
    edit1 = driver.find_element(By.XPATH,
                                "//a[. = '\n\t\t\t\tEdit']")
    edit1.click()

    # 23. Click 'SELECT24'
    select24 = driver.find_element(By.XPATH,
                                   "//div[2]/div/select")
    select24.click()

    # 24. Select the 'Customer' option in 'SELECT24'
    select24 = driver.find_element(By.XPATH,
                                   "//div[2]/div/select")
    Select(select24).select_by_value("Customer")

    # 25. Click 'SELECT24'
    select24 = driver.find_element(By.XPATH,
                                   "//div[2]/div/select")
    select24.click()

    # 26. Click 'INPUT133'
    input133 = driver.find_element(By.XPATH,
                                   "//div[2]/div/div[2]/div[1]/div/div[2]/div/div/div/form//input")
    input133.click()

    # 27. Click '2015 Halladay Wellness, Inc1'
    _2015_halladay_wellness_inc1 = driver.find_element(By.XPATH,
                                                       "//strong[. = '2015 Halladay Wellness, Inc']")
    _2015_halladay_wellness_inc1.click()

    # 28. Click 'Update'
    update = driver.find_element(By.XPATH,
                                 "//button[. = 'Update']")
    update.click()

    # 29. Does 'Updated successfully13' contain 'Updated successfully'?
    updated_successfully13 = driver.find_element(By.XPATH,
                                                 "//div[. = 'Updated successfully']")
    step_output = updated_successfully13.text
    assert step_output and ("Updated successfully" in step_output)

    # # 30. Click 'Test code'
    # test_code = driver.find_element(By.XPATH,
    #                                 "//a[. = '\n\t\t\t\tTest code\n\t\t\t\t']")
    # test_code.click()
    #
    # # 31. Scroll window by ('0','300')
    # driver.execute_script("window.scrollBy(0,300)")
    #
    # # 32. Scroll window by ('0','300')
    # driver.execute_script("window.scrollBy(0,300)")
    #
    # # 33. Scroll window by ('0','300')
    # driver.execute_script("window.scrollBy(0,300)")
    #
    # # 34. Scroll window by ('0','200')
    # driver.execute_script("window.scrollBy(0,200)")
    #
    # # # 35. Scroll window by ('0','300')
    # # driver.execute_script("window.scrollBy(0,300)")
    # #
    # # # 36. Scroll window by ('0','-600')
    # # driver.execute_script("window.scrollBy(0,-600)")
    # #
    # # # 37. Scroll window by ('0','-200')
    # # driver.execute_script("window.scrollBy(0,-200)")
    # #
    # # # 38. Scroll window by ('0','-200')
    # # driver.execute_script("window.scrollBy(0,-200)")
    #
    # # 39. Scroll window by ('0','400')
    # driver.execute_script("window.scrollBy(0,400)")
    #
    # # 40. Scroll window by ('0','100')
    # driver.execute_script("window.scrollBy(0,100)")
    #
    # # 41. Get text from 'INPUT127'
    # # captured item Name
    # input127 = driver.find_element(By.XPATH,
    #                                "//div[3]/div/div[1]/form/div[4]//input")
    # step_output = input127.get_attribute("value")

    # 42. Click 'Settings2'
    settings2 = driver.find_element(By.XPATH,
                                    "//span[. = '      Settings']")
    settings2.click()

    # 43. Click 'Logout1'
    logout1 = driver.find_element(By.XPATH,
                                  "//a[. = '       Logout']")
    logout1.click()

    # 44. Scroll window by ('0','-900')
    driver.execute_script("window.scrollBy(0,-900)")

    # 45. Does 'Login' contain 'Login'?
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    step_output = login.text
    assert step_output and ("Login" in step_output)
