import time

from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Bloomy_Core
    Package: TestProject.Generated.Tests.BloomyCore
    Test: CreateLead_TestCase01
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 05/26/2021, 13:20:18
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Bloomy_Core",
                              job_name="CreateLead_TestCase01")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("testautomationuser@bloomstack.com")

    # 5. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 6. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 7. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 8. Click 'CRM'
    crm = driver.find_element(By.XPATH,
                              "//div[. = '\n                CRM\n              ']")
    crm.click()

    # 9. Does 'CRM1' contain 'CRM'?
    crm1 = driver.find_element(By.XPATH,
                               "//div[. = 'CRM']")
    step_output = crm1.text
    assert step_output and ("CRM" in step_output)

    # 10. Click 'Lead'
    lead = driver.find_element(By.XPATH,
                               "//div/a[. = 'Lead']")
    lead.click()

    # 11. Does 'Lead1' contain 'Lead'?
    lead1 = driver.find_element(By.XPATH,
                                "//div[. = 'Lead']")
    step_output = lead1.text
    assert step_output and ("Lead" in step_output)
    time.sleep(2)

    # 12. Click 'New'
    new = driver.find_element(By.XPATH,
                              "//span[. = 'New']")
    new.click()

    # 13. Scroll window by ('0','205')
    driver.execute_script("window.scrollBy(0,205)")

    # 14. Does 'DIV4' contain '[NONE]'?
    div4 = driver.find_element(By.XPATH,
                               "//div[4]/div[1]/div/div/div[1]/h1/div[2]")
    step_output = div4.text
    assert step_output and ("" in step_output)

    # 15. Does 'DIV4' contain '[NONE]'?
    div4 = driver.find_element(By.XPATH,
                               "//div[4]/div[1]/div/div/div[1]/h1/div[2]")
    step_output = div4.text
    assert step_output and ("" in step_output)

    # 16. Scroll window by ('0','494')
    driver.execute_script("window.scrollBy(0,494)")

    # 17. Scroll window by ('0','-200')
    driver.execute_script("window.scrollBy(0,-200)")

    # 18. Scroll window by ('0','-300')
    driver.execute_script("window.scrollBy(0,-300)")

    # 19. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//div[4]/div[2]/div[1]/form/div[2]//input")
    input.click()

    # 20. Type 'Rahul Tester' in 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//div[4]/div[2]/div[1]/form/div[2]//input")
    input.send_keys("Rahul Tester")
    time.sleep(2)

    # 21. Click 'Save2'
    save2 = driver.find_element(By.XPATH,
                                "//button[. = 'Save']")
    driver.execute_script("arguments[0].click();", save2)

    # 22. Scroll window by ('0','-200')
    driver.execute_script("window.scrollBy(0,-200)")

    # 23. Does 'Saved' contain 'Saved'?
    saved = driver.find_element(By.XPATH,
                                "//div[. = 'Saved']")
    step_output = saved.text
    assert step_output and ("Saved" in step_output)

    # 24. Does 'DIV4' contain '[NONE]'?
    div4 = driver.find_element(By.XPATH,
                               "//div[4]/div[1]/div/div/div[1]/h1/div[2]")
    step_output = div4.text
    assert step_output and ("" in step_output)

    # 26. Click 'Lead2'
    lead2 = driver.find_element(By.XPATH,
                                "//li[2]/a[. = 'Lead']")
    lead2.click()

    # 27. Click 'Settings'
    settings = driver.find_element(By.XPATH,
                                   "//span[. = '      Settings']")
    settings.click()

    # 28. Click 'Logout'
    logout = driver.find_element(By.XPATH,
                                 "//a[. = '       Logout']")
    logout.click()
