from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Demo_ Bloomy
    Package: TestProject.Generated.Tests.DemoBloomy
    Test: DeleteAsset_TestCase01
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 04/05/2021, 04:46:56
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Demo_ Bloomy",
                              job_name="DeleteAsset_TestCase01")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("rahul.prakash@extrapreneursindia.com")

    # 5. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 6. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 7. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 8. Click 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.click()

    # 9. Type 'Asset' in 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.send_keys("Asset")

    # 10. Click 'New Asset'
    new_asset = driver.find_element(By.XPATH,
                                    "//p[. = 'New Asset']")
    new_asset.click()

    # 11. Does 'New Asset 11' contain 'New Asset 1'?
    new_asset_11 = driver.find_element(By.XPATH,
                                       "//div[. = 'New Asset 1']")
    step_output = new_asset_11.text
    assert step_output and ("New Asset 1" in step_output)

    # 12. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//div[2]/div/div[2]/form/div[1]//input")
    input.click()

    # 13. Type 'vap' in 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//div[2]/div/div[2]/form/div[1]//input")
    input.send_keys("vap")

    # 14. Click 'VapeCo3'
    vapeco3 = driver.find_element(By.XPATH,
                                  "//strong[. = 'VapeCo']")
    vapeco3.click()

    # 15. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//div[2]/div/div[1]/form/div[3]//input")
    input1.click()

    # 16. Type 'Deleted Asset' in 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//div[2]/div/div[1]/form/div[3]//input")
    input1.send_keys("Deleted Asset")

    # 17. Click 'INPUT2'
    input2 = driver.find_element(By.XPATH,
                                 "//div[1]/form/div[4]//input")
    input2.click()

    # 18. Click 'INPUT3'
    input3 = driver.find_element(By.XPATH,
                                 "//div[2]/div/div[2]/div[1]/div/div/input")
    input3.click()

    # 19. Click 'india2'
    india2 = driver.find_element(By.XPATH,
                                 "//li[. = 'india']")
    india2.click()

    # 20. Click 'INPUT2'
    input2 = driver.find_element(By.XPATH,
                                 "//div[1]/form/div[4]//input")
    input2.click()

    # 21. Click 'LI'
    li = driver.find_element(By.XPATH,
                             "//div[2]/div[1]/div/div/ul/li[7]")
    li.click()

    # 22. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 23. Click 'INPUT4'
    input4 = driver.find_element(By.XPATH,
                                 "//div[2]/div/div[2]/form/div[5]//input")
    input4.click()

    # 24. Click 'svg'
    svg = driver.find_element(By.XPATH,
                              "//div[1]/nav/div[3]/*")
    svg.click()

    # 25. Click 'svg'
    svg = driver.find_element(By.XPATH,
                              "//div[1]/nav/div[3]/*")
    svg.click()

    # 26. Click '30'
    _30 = driver.find_element(By.XPATH,
                              "//div[32][. = '30']")
    _30.click()

    # 27. Click 'INPUT5'
    input5 = driver.find_element(By.XPATH,
                                 "//div[2]/form/div[8]//input")
    input5.click()

    # 28. Click 'MAT-PRE-2020-00128'
    mat_pre_2020_00128 = driver.find_element(By.XPATH,
                                             "//strong[. = 'MAT-PRE-2020-00128']")
    mat_pre_2020_00128.click()

    # 29. Click 'Save'
    save = driver.find_element(By.XPATH,
                               "//span[. = 'Save']")
    save.click()

    # 30. Scroll window by ('0','-100')
    driver.execute_script("window.scrollBy(0,-100)")

    # 31. Does 'Saved' contain 'Saved'?
    saved = driver.find_element(By.XPATH,
                                "//div[. = 'Saved']")
    step_output = saved.text
    assert step_output and ("Saved" in step_output)

    # 32. Click 'Asset'
    asset = driver.find_element(By.XPATH,
                                "//li[2]/a[. = 'Asset']")
    asset.click()

    # 33. Click 'INPUT17'
    input17 = driver.find_element(By.XPATH,
                                  "//div[2]/div[2]/div[1]/div[1]/div/input")
    input17.click()

    # 34. Click 'Actions'
    actions = driver.find_element(By.XPATH,
                                  "//div[3]//button[. = '               Actions                            ']")
    actions.click()

    # 35. Click 'Delete'
    delete = driver.find_element(By.XPATH,
                                 "//a[. = '\n\t\t\t\tDelete']")
    delete.click()

    # 36. Click 'Yes3'
    yes3 = driver.find_element(By.XPATH,
                               "//button[. = 'Yes']")
    yes3.click()

    # 37. Does 'Asset1' contain 'Asset'?
    asset1 = driver.find_element(By.XPATH,
                                 "//div[. = 'Asset']")
    step_output = asset1.text
    assert step_output and ("Asset" in step_output)

    # 38. Click 'Settings'
    settings = driver.find_element(By.XPATH,
                                   "//span[. = '      Settings']")
    settings.click()

    # 39. Click 'Logout'
    logout = driver.find_element(By.XPATH,
                                 "//a[. = '       Logout']")
    logout.click()
