from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Demo_ Bloomy
    Package: TestProject.Generated.Tests.DemoBloomy
    Test: DeletePurchaseOrder_TestCase01
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 03/09/2021, 11:01:19
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Demo_ Bloomy",
                              job_name="DeletePurchaseOrder_TestCase01")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("rahul.prakash@extrapreneursindia.com")

    # 5. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 6. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 7. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 8. Click 'Purchasing'
    purchasing = driver.find_element(By.XPATH,
                                     "//div[. = '\n                Purchasing\n              ']")
    purchasing.click()

    # 9. Does 'Purchasing1' contain 'Purchasing'?
    purchasing1 = driver.find_element(By.XPATH,
                                      "//div[. = 'Purchasing']")
    step_output = purchasing1.text
    assert step_output and ("Purchasing" in step_output)

    # 10. Click 'Purchase Order'
    purchase_order = driver.find_element(By.XPATH,
                                         "//div/a[. = 'Purchase Order']")
    purchase_order.click()

    # 11. Does 'Purchase Order1' contain 'Purchase Order'?
    purchase_order1 = driver.find_element(By.XPATH,
                                          "//div[. = 'Purchase Order']")
    step_output = purchase_order1.text
    assert step_output and ("Purchase Order" in step_output)

    # 12. Click 'New'
    new = driver.find_element(By.XPATH,
                              "//span[. = 'New']")
    new.click()

    # 13. Click 'INPUT21'
    input21 = driver.find_element(By.XPATH,
                                  "//div[3]/div/div[1]/form/div[3]//input")
    input21.click()

    # 14. Type 'epi' in 'INPUT21'
    input21 = driver.find_element(By.XPATH,
                                  "//div[3]/div/div[1]/form/div[3]//input")
    input21.send_keys("epi")

    # 15. Click 'P39'
    p39 = driver.find_element(By.XPATH,
                              "//li[3]//p")
    p39.click()

    # 16. Click 'INPUT41'
    input41 = driver.find_element(By.XPATH,
                                  "//div[1]/form/div[6]//input")
    input41.click()

    # 17. Type 'extra' in 'INPUT41'
    input41 = driver.find_element(By.XPATH,
                                  "//div[1]/form/div[6]//input")
    input41.send_keys("extra")

    # 18. Click 'Extrapreneurs India Pvt Ltd3'
    extrapreneurs_india_pvt_ltd3 = driver.find_element(By.XPATH,
                                                       "//strong[. = 'Extrapreneurs India Pvt Ltd']")
    extrapreneurs_india_pvt_ltd3.click()

    # 19. Click 'INPUT28'
    input28 = driver.find_element(By.XPATH,
                                  "//div[3]/div/div[2]/form/div[2]//input")
    input28.click()

    # 20. Click '314'
    _314 = driver.find_element(By.XPATH,
                               "//div[2]/div//div[. = '31']")
    _314.click()

    # 21. Scroll window by ('0','200')
    driver.execute_script("window.scrollBy(0,200)")

    # 22. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 23. Click 'INPUT42'
    input42 = driver.find_element(By.XPATH,
                                  "//div[7]/div/div[1]/form//input")
    input42.click()

    # 24. Click 'EPI-Warehouse3 - EIPL'
    epi_warehouse3_eipl = driver.find_element(By.XPATH,
                                              "//strong[. = 'EPI-Warehouse3 - EIPL']")
    epi_warehouse3_eipl.click()

    # 25. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 26. Click 'DIV27'
    div27 = driver.find_element(By.XPATH,
                                "//div[2]/div/div[2]/div[2]/div[1]/div/div/div[2]")
    div27.click()

    # 27. Type 'epi' in 'Item Code'
    item_code = driver.find_element(By.XPATH,
                                    "//input[@placeholder = 'Item Code']")
    item_code.send_keys("epi")

    # 28. Click 'EPI-Chocolate, EPI-Item Group1,'
    epi_chocolate_epi_item_group1_ = driver.find_element(By.XPATH,
                                                         "//span[. = 'EPI-Chocolate, EPI-Item Group1, ']")
    epi_chocolate_epi_item_group1_.click()

    # 29. Scroll window by ('0','-58')
    driver.execute_script("window.scrollBy(0,-58)")

    # 30. Click 'Save'
    save = driver.find_element(By.XPATH,
                               "//span[. = 'Save']")
    save.click()

    # 31. Scroll window by ('0','-342')
    driver.execute_script("window.scrollBy(0,-342)")

    # 32. Does 'Saved12' contain 'Saved'?
    saved12 = driver.find_element(By.XPATH,
                                  "//div[. = 'Saved']")
    step_output = saved12.text
    assert step_output and ("Saved" in step_output)

    # 33. Click 'Purchase Order4'
    purchase_order4 = driver.find_element(By.XPATH,
                                          "//div[1]/ul//a[. = 'Purchase Order']")
    purchase_order4.click()

    # 34. Click 'INPUT40'
    input40 = driver.find_element(By.XPATH,
                                  "//div[2]/div[2]/div[1]/div[1]/div/input")
    input40.click()

    # 35. Click 'Actions'
    actions = driver.find_element(By.XPATH,
                                  "//div[3]//button[. = '               Actions                            ']")
    actions.click()

    # 36. Click 'Delete2'
    delete2 = driver.find_element(By.XPATH,
                                  "//a[. = '\n\t\t\t\tDelete']")
    delete2.click()

    # 37. Click 'Yes'
    yes = driver.find_element(By.XPATH,
                              "//button[. = 'Yes']")
    yes.click()

    # 38. Click 'INPUT38'
    input38 = driver.find_element(By.XPATH,
                                  "//div[2]/div[2]/div[1]/div[1]/div/input")
    input38.click()

    # 39. Click 'Actions'
    actions = driver.find_element(By.XPATH,
                                  "//div[3]//button[. = '               Actions                            ']")
    actions.click()

    # 40. Click 'Delete2'
    delete2 = driver.find_element(By.XPATH,
                                  "//a[. = '\n\t\t\t\tDelete']")
    delete2.click()

    # 41. Click 'Yes4'
    yes4 = driver.find_element(By.XPATH,
                               "//div[2]/div/div//button[. = 'Yes']")
    yes4.click()
