from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Demo_ Bloomy
    Package: TestProject.Generated.Tests.DemoBloomy
    Test: DeletePaymentEntry_TestCase01
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 04/07/2021, 03:36:04
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Demo_ Bloomy",
                              job_name="DeletePaymentEntry_TestCase01")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("rahul.prakash@extrapreneursindia.com")

    # 5. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 6. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 7. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 8. Click 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.click()

    # 9. Type 'sales order' in 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.send_keys("sales order")

    # 10. Click 'Sales Order2'
    sales_order2 = driver.find_element(By.XPATH,
                                       "//li[4]//b[. = 'Sales Order']")
    sales_order2.click()

    # 11. Click 'INPUT22'
    input22 = driver.find_element(By.XPATH,
                                  "//div[3]/div/div[2]/form/div[2]//input")
    input22.click()

    # 12. Does 'New Sales Order 12' contain 'New Sales Order 1'?
    new_sales_order_12 = driver.find_element(By.XPATH,
                                             "//div[. = 'New Sales Order 1']")
    step_output = new_sales_order_12.text
    assert step_output and ("New Sales Order 1" in step_output)

    # 13. Click 'INPUT22'
    input22 = driver.find_element(By.XPATH,
                                  "//div[3]/div/div[2]/form/div[2]//input")
    input22.click()

    # 14. Type 'vap' in 'INPUT22'
    input22 = driver.find_element(By.XPATH,
                                  "//div[3]/div/div[2]/form/div[2]//input")
    input22.send_keys("vap")

    # 15. Click 'INPUT22'
    input22 = driver.find_element(By.XPATH,
                                  "//div[3]/div/div[2]/form/div[2]//input")
    input22.click()

    # 16. Type 'va' in 'INPUT22'
    input22 = driver.find_element(By.XPATH,
                                  "//div[3]/div/div[2]/form/div[2]//input")
    input22.send_keys("va")

    # 17. Click 'VapeCo5'
    vapeco5 = driver.find_element(By.XPATH,
                                  "//strong[. = 'VapeCo']")
    vapeco5.click()

    # 18. Click 'INPUT23'
    input23 = driver.find_element(By.XPATH,
                                  "//div[3]/div/div[1]/form/div[3]//input")
    input23.click()

    # 19. Click 'P3'
    p3 = driver.find_element(By.XPATH,
                             "//div[3]/div/div[2]/div[1]/div/div/ul/li[1]//p")
    p3.click()

    # 20. Click 'Expected Delivery Date'
    expected_delivery_date = driver.find_element(By.XPATH,
                                                 "//label[. = 'Expected Delivery Date']")
    expected_delivery_date.click()

    # 21. Click 'INPUT24'
    input24 = driver.find_element(By.XPATH,
                                  "//form/div[4]/div/div[2]/div/input")
    input24.click()

    # 22. Click 'svg2'
    svg2 = driver.find_element(By.XPATH,
                               "//div[2]/nav/div[3]/*")
    svg2.click()

    # 23. Click '311'
    _311 = driver.find_element(By.XPATH,
                               "//div[37][. = '31']")
    _311.click()

    # 24. Scroll window by ('0','200')
    driver.execute_script("window.scrollBy(0,200)")

    # 25. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 26. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 27. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 28. Click 'DIV7'
    div7 = driver.find_element(By.XPATH,
                               "//div[2]/div/div[2]/div[2]/div[1]/div/div/div[2]")
    div7.click()

    # 29. Click 'Finished Oil, Dry Goods, Extracted Ja...'
    finished_oil_dry_goods_extracted_ja_ = driver.find_element(By.XPATH,
                                                               "//span[. = 'Finished Oil, Dry Goods, Extracted Jack Herer Cannabis Oil']")
    finished_oil_dry_goods_extracted_ja_.click()

    # 30. Click 'Save11'
    save11 = driver.find_element(By.XPATH,
                                 "//span[. = 'Save']")
    save11.click()

    # 31. Scroll window by ('0','-500')
    driver.execute_script("window.scrollBy(0,-500)")

    # 32. Click 'Close1'
    close1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\tClose\n\t\t\t\t\t\t\t\t']")
    close1.click()

    # 33. Does 'Saved8' contain 'Saved'?
    saved8 = driver.find_element(By.XPATH,
                                 "//div[. = 'Saved']")
    step_output = saved8.text
    assert step_output and ("Saved" in step_output)

    # 34. Does 'Draft' contain 'Draft'?
    draft = driver.find_element(By.XPATH,
                                "//span/span[. = 'Draft']")
    step_output = draft.text
    assert step_output and ("Draft" in step_output)

    # 35. Click 'Submit9'
    submit9 = driver.find_element(By.XPATH,
                                  "//button[. = 'Submit']")
    submit9.click()

    # 36. Click 'Yes'
    yes = driver.find_element(By.XPATH,
                              "//button[. = 'Yes']")
    yes.click()

    # 37. Click 'Close2'
    close2 = driver.find_element(By.XPATH,
                                 "//span[. = 'Close']")
    close2.click()

    # 38. Does 'Sales Order has been submitted succes...1' contain 'Sales Order has been submitted successfully'?
    sales_order_has_been_submitted_succes_1 = driver.find_element(By.XPATH,
                                                                  "//div[. = 'Sales Order has been submitted successfully']")
    step_output = sales_order_has_been_submitted_succes_1.text
    assert step_output and (
        "Sales Order has been submitted successfully" in step_output)

    # 39. Click 'I6'
    i6 = driver.find_element(By.XPATH,
                             "//div[1]/div[1]/div[1]/button/i")
    i6.click()

    # 40. Does 'New Sales Invoice 13' contain 'New Sales Invoice 1'?
    new_sales_invoice_13 = driver.find_element(By.XPATH,
                                               "//div[. = 'New Sales Invoice 1']")
    step_output = new_sales_invoice_13.text
    assert step_output and ("New Sales Invoice 1" in step_output)

    # 41. Click 'SELECT4'
    select4 = driver.find_element(By.XPATH,
                                  "//div[3]/div[2]/div[2]/div/div[3]/div[2]/div[1]/div[3]/div/div/div[2]/div[3]/div/div[1]/form/div[2]//select")
    select4.click()

    # 42. Select the 'ACC-SINV-.YYYY.-' option in 'SELECT4'
    select4 = driver.find_element(By.XPATH,
                                  "//div[3]/div[2]/div[2]/div/div[3]/div[2]/div[1]/div[3]/div/div/div[2]/div[3]/div/div[1]/form/div[2]//select")
    Select(select4).select_by_value("ACC-SINV-.YYYY.-")

    # 43. Click 'SELECT4'
    select4 = driver.find_element(By.XPATH,
                                  "//div[3]/div[2]/div[2]/div/div[3]/div[2]/div[1]/div[3]/div/div/div[2]/div[3]/div/div[1]/form/div[2]//select")
    select4.click()

    # 44. Click 'Save13'
    save13 = driver.find_element(By.XPATH,
                                 "//button[. = 'Save']")
    save13.click()

    # 45. Click 'Close3'
    close3 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\tClose\n\t\t\t\t\t\t\t\t']")
    close3.click()

    # 46. Does 'Saved9' contain 'Saved'?
    saved9 = driver.find_element(By.XPATH,
                                 "//div[4]/div[. = 'Saved']")
    step_output = saved9.text
    assert step_output and ("Saved" in step_output)

    # 47. Does 'Draft5' contain 'Draft'?
    draft5 = driver.find_element(By.XPATH,
                                 "//span/span[. = 'Draft']")
    step_output = draft5.text
    assert step_output and ("Draft" in step_output)

    # 48. Click 'Submit6'
    submit6 = driver.find_element(By.XPATH,
                                  "//div[3]//span[. = 'Submit']")
    submit6.click()

    # 49. Click 'Yes2'
    yes2 = driver.find_element(By.XPATH,
                               "//div[2]/div/div//button[. = 'Yes']")
    yes2.click()

    # 50. Click 'Close2'
    close2 = driver.find_element(By.XPATH,
                                 "//span[. = 'Close']")
    close2.click()

    # 51. Does 'Sales Invoice has been submitted succ...2' contain 'Sales Invoice has been submitted successfully'?
    sales_invoice_has_been_submitted_succ_2 = driver.find_element(By.XPATH,
                                                                  "//div[. = 'Sales Invoice has been submitted successfully']")
    step_output = sales_invoice_has_been_submitted_succ_2.text
    assert step_output and (
        "Sales Invoice has been submitted successfully" in step_output)

    # 52. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[3]/div[2]/div[2]/div/div[3]/div[2]/div[1]/div[3]/div/div/div[2]/div[1]/div[2]/div/div[5]/div/div/div[1]/div[1]/div[1]//i")
    i5.click()

    # 53. Does 'New Payment Entry 13' contain 'New Payment Entry 1'?
    new_payment_entry_13 = driver.find_element(By.XPATH,
                                               "//div[. = 'New Payment Entry 1']")
    step_output = new_payment_entry_13.text
    assert step_output and ("New Payment Entry 1" in step_output)

    # 54. Click 'INPUT25'
    input25 = driver.find_element(By.XPATH,
                                  "//div[3]/div[2]/div[2]/form/div[3]//input")
    input25.click()

    # 55. Type 'cash' in 'INPUT25'
    input25 = driver.find_element(By.XPATH,
                                  "//div[3]/div[2]/div[2]/form/div[3]//input")
    input25.send_keys("cash")

    # 56. Click 'Cash9'
    cash9 = driver.find_element(By.XPATH,
                                "//p[. = 'Cash']")
    cash9.click()

    # 57. Does 'Payment Entry' contain 'Payment Entry'?
    payment_entry = driver.find_element(By.XPATH,
                                        "//li/a[. = 'Payment Entry']")
    step_output = payment_entry.text
    assert step_output and ("Payment Entry" in step_output)

    # 58. Click 'Save14'
    save14 = driver.find_element(By.XPATH,
                                 "//button[. = 'Save']")
    save14.click()

    # 59. Does 'Saved16' contain 'Saved'?
    saved16 = driver.find_element(By.XPATH,
                                  "//div[7]/div[. = 'Saved']")
    step_output = saved16.text
    assert step_output and ("Saved" in step_output)

    # 60. Does 'Draft4' contain 'Draft'?
    draft4 = driver.find_element(By.XPATH,
                                 "//span/span[. = 'Draft']")
    step_output = draft4.text
    assert step_output and ("Draft" in step_output)

    # 61. Click 'Payment Entry'
    payment_entry = driver.find_element(By.XPATH,
                                        "//li/a[. = 'Payment Entry']")
    payment_entry.click()

    # 62. Click 'INPUT26'
    input26 = driver.find_element(By.XPATH,
                                  "//div[2]/div[2]/div[1]/div[1]/div/input")
    input26.click()

    # 63. Click 'SPAN2'
    span2 = driver.find_element(By.XPATH,
                                "//div[5]/div[1]/div/div/div[2]/div[2]/button/span/span[2]")
    span2.click()

    # 64. Click 'Delete1'
    delete1 = driver.find_element(By.XPATH,
                                  "//a[. = '\n\t\t\t\tDelete']")
    delete1.click()

    # 65. Click 'Yes2'
    yes2 = driver.find_element(By.XPATH,
                               "//div[2]/div/div//button[. = 'Yes']")
    yes2.click()

    # 66. Does '20 of 422' contain '20 of 422'?
    _20_of_422 = driver.find_element(By.XPATH,
                                     "//span/span[. = '20 of 422']")
    step_output = _20_of_422.text
    assert step_output and ("20 of 422" in step_output)

    # 67. Does 'Payment Entry1' contain 'Payment Entry'?
    payment_entry1 = driver.find_element(By.XPATH,
                                         "//div[. = 'Payment Entry']")
    step_output = payment_entry1.text
    assert step_output and ("Payment Entry" in step_output)

    # 68. Click 'Settings'
    settings = driver.find_element(By.XPATH,
                                   "//span[. = '      Settings']")
    settings.click()

    # 69. Click 'Logout'
    logout = driver.find_element(By.XPATH,
                                 "//a[. = '       Logout']")
    logout.click()
