from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Demo_ Bloomy
    Package: TestProject.Generated.Tests.DemoBloomy
    Test: DeletePackingSlip_TestCase02
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 03/22/2021, 07:56:30
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Demo_ Bloomy",
                              job_name="DeletePackingSlip_TestCase02")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"
    GridValue = "Does20of33spancontain\"20of33\"?"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 5. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("rahul.prakash@extrapreneursindia.com")

    # 6. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 7. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 8. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 9. Click 'Stock4'
    stock4 = driver.find_element(By.XPATH,
                                 "//div[. = '\n                Stock\n              ']")
    stock4.click()

    # 10. Does 'Stock1' contain 'Stock'?
    stock1 = driver.find_element(By.XPATH,
                                 "//div[. = 'Stock']")
    step_output = stock1.text
    assert step_output and ("Stock" in step_output)

    # 11. Click 'Delivery Note'
    delivery_note = driver.find_element(By.XPATH,
                                        "//div/a[. = 'Delivery Note']")
    delivery_note.click()

    # 12. Does 'Delivery Note1' contain 'Delivery Note'?
    delivery_note1 = driver.find_element(By.XPATH,
                                         "//div[. = 'Delivery Note']")
    step_output = delivery_note1.text
    assert step_output and ("Delivery Note" in step_output)

    # 13. Click 'New'
    new = driver.find_element(By.XPATH,
                              "//button[. = 'New']")
    new.click()

    # 14. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//div[2]/form/div[2]/div/div[2]/div[1]/div//input")
    input.click()

    # 15. Type 'vap' in 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//div[2]/form/div[2]/div/div[2]/div[1]/div//input")
    input.send_keys("vap")

    # 16. Click 'VapeCo3'
    vapeco3 = driver.find_element(By.XPATH,
                                  "//li[. = 'VapeCo']")
    vapeco3.click()

    # 17. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//div[3]/div[2]/div[1]/form//input")
    input1.click()

    # 18. Click 'P2'
    p2 = driver.find_element(By.XPATH,
                             "//div[3]/div/div[2]/div[1]/div/div/ul/li[1]//p")
    p2.click()

    # 19. Scroll window by ('0','300')
    driver.execute_script("window.scrollBy(0,300)")

    # 20. Scroll window by ('0','300')
    driver.execute_script("window.scrollBy(0,300)")

    # 21. Click 'DIV'
    div = driver.find_element(By.XPATH,
                              "//div[2]/div/div[2]/div[2]/div[1]/div/div/div[2]")
    div.click()

    # 22. Click 'VC-CB-CO-CCL-0001'
    vc_cb_co_ccl_0001 = driver.find_element(By.XPATH,
                                            "//strong[. = 'VC-CB-CO-CCL-0001']")
    vc_cb_co_ccl_0001.click()

    # 23. Does 'DIV15' contain '[NONE]'?
    div15 = driver.find_element(By.XPATH,
                                "//div[5]/div[2]/div/div[1]/div/div[1]")
    step_output = div15.text
    assert step_output and ("" in step_output)

    # 24. Click 'Insert'
    insert = driver.find_element(By.XPATH,
                                 "//button[. = 'Insert']")
    insert.click()

    # 25. Click 'Save1'
    save1 = driver.find_element(By.XPATH,
                                "//span[. = 'Save']")
    save1.click()

    # 26. Scroll window by ('0','-600')
    driver.execute_script("window.scrollBy(0,-600)")

    # 27. Click 'Close5'
    close5 = driver.find_element(By.XPATH,
                                 "//div[2]/div/div//span[. = 'Close']")
    close5.click()

    # 28. Does 'Saved' contain 'Saved'?
    saved = driver.find_element(By.XPATH,
                                "//div[. = 'Saved']")
    step_output = saved.text
    assert step_output and ("Saved" in step_output)

    # 29. Click ''
    _ = driver.find_element(By.XPATH,
                            "//div[1]/div[2]/button[. = '        ']")
    _.click()

    # 30. Does 'DIV9' contain '[NONE]'?
    div9 = driver.find_element(By.XPATH,
                               "//div[5]/div[1]/div/div/div[1]/h1/div[2]")
    step_output = div9.text
    assert step_output and ("" in step_output)

    # 31. Scroll window by ('0','300')
    driver.execute_script("window.scrollBy(0,300)")

    # 32. Scroll window by ('0','-100')
    driver.execute_script("window.scrollBy(0,-100)")

    # 33. Click 'INPUT27'
    input27 = driver.find_element(By.XPATH,
                                  "//div[5]/div/div[1]/form/div[1]//input")
    input27.click()

    # 34. Click 'DT warehouse - VC'
    dt_warehouse_vc = driver.find_element(By.XPATH,
                                          "//p[. = 'DT warehouse - VC']")
    dt_warehouse_vc.click()

    # 35. Click 'Save9'
    save9 = driver.find_element(By.XPATH,
                                "//span[. = 'Save']")
    save9.click()

    # 36. Scroll window by ('0','-200')
    driver.execute_script("window.scrollBy(0,-200)")

    # 37. Does 'Saved1' contain 'Saved'?
    saved1 = driver.find_element(By.XPATH,
                                 "//div[2]/div[. = 'Saved']")
    step_output = saved1.text
    assert step_output and ("Saved" in step_output)

    # 38. Click 'Packing Slip1'
    packing_slip1 = driver.find_element(By.XPATH,
                                        "//header//a[. = 'Packing Slip']")
    packing_slip1.click()

    # 39. Does 'DIV16' contain '[NONE]'?
    div16 = driver.find_element(By.XPATH,
                                "//body/div[1]/div/div[6]/div[1]/div/div/div[1]")
    step_output = div16.text
    assert step_output and ("" in step_output)

    # 40. Click 'INPUT28'
    input28 = driver.find_element(By.XPATH,
                                  "//div[6]/div[2]/div[2]/div/div[3]/div[2]/div[1]/div[3]/div[2]/div[2]/div[1]//input")
    input28.click()

    # 41. Click 'SPAN5'
    span5 = driver.find_element(By.XPATH,
                                "//div[6]/div[1]/div/div/div[2]/div[2]/button/span[1]")
    span5.click()

    # 42. Click 'Delete3'
    delete3 = driver.find_element(By.XPATH,
                                  "//li[13]/a[. = '\n\t\t\t\tDelete']")
    delete3.click()

    # 43. Click 'Yes2'
    yes2 = driver.find_element(By.XPATH,
                               "//button[. = 'Yes']")
    yes2.click()

    # 44. Does '20 of 33' contain '20 of 33'?
    if float(f'{GridValue}') <= float("Does20of33spancontain\"20of33\"?"):
        _20_of_33 = driver.find_element(By.XPATH,
                                        "//span/span[. = '20 of 33']")
        step_output = _20_of_33.text
        assert step_output and ("20 of 33" in step_output)

    # 45. Click 'Settings'
    settings = driver.find_element(By.XPATH,
                                   "//span[. = '      Settings']")
    settings.click()

    # 46. Click 'Logout'
    logout = driver.find_element(By.XPATH,
                                 "//a[. = '       Logout']")
    logout.click()
