import time

from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Demo_ Bloomy
    Package: TestProject.Generated.Tests.DemoBloomy
    Test: UpdateStockEntry_TestCase01
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 03/24/2021, 05:59:20
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Demo_ Bloomy",
                              job_name="UpdateStockEntry_TestCase01")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("rahul.prakash@extrapreneursindia.com")

    # 5. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 6. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 7. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 8. Click 'Stock5'
    stock5 = driver.find_element(By.XPATH,
                                 "//div[. = '\n                Stock\n              ']")
    stock5.click()

    # 9. Does 'Stock2' contain 'Stock'?
    stock2 = driver.find_element(By.XPATH,
                                 "//div[. = 'Stock']")
    step_output = stock2.text
    assert step_output and ("Stock" in step_output)

    # 10. Click 'Stock Entry'
    stock_entry = driver.find_element(By.XPATH,
                                      "//div/a[. = 'Stock Entry']")
    stock_entry.click()

    # 11. Does 'Stock Entry2' contain 'Stock Entry'?
    stock_entry2 = driver.find_element(By.XPATH,
                                       "//div[. = 'Stock Entry']")
    step_output = stock_entry2.text
    assert step_output and ("Stock Entry" in step_output)
    time.sleep(2)

    # 12. Click 'New'
    new = driver.find_element(By.XPATH,
                              "//button[. = 'New']")
    new.click()

    # 13. Does 'New Stock Entry 1' contain 'New Stock Entry 1'?
    new_stock_entry_1 = driver.find_element(By.XPATH,
                                            "//div[. = 'New Stock Entry 1']")
    step_output = new_stock_entry_1.text
    assert step_output and ("New Stock Entry 1" in step_output)

    # 14. Click 'INPUT47'
    input47 = driver.find_element(By.XPATH,
                                  "//div[3]/div/div[1]/form/div[3]//input")
    input47.click()

    # 15. Click 'Material Issue'
    material_issue = driver.find_element(By.XPATH,
                                         "//li[. = 'Material Issue']")
    material_issue.click()

    # 16. Click 'INPUT48'
    input48 = driver.find_element(By.XPATH,
                                  "//div[6]/div/div[2]//input")
    input48.click()

    # 17. Type 'vap' in 'INPUT48'
    input48 = driver.find_element(By.XPATH,
                                  "//div[6]/div/div[2]//input")
    input48.send_keys("vap")

    # 18. Click 'VapeCo7'
    vapeco7 = driver.find_element(By.XPATH,
                                  "//li[. = 'VapeCo']")
    vapeco7.click()

    # 19. Scroll window by ('0','300')
    driver.execute_script("window.scrollBy(0,300)")

    # 20. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 21. Click 'DIV20'
    div20 = driver.find_element(By.XPATH,
                                "//div[2]/div/div[2]/div[2]/div[1]/div/div/div[2]")
    div20.click()

    # 22. Click 'DT warehouse - VC5'
    dt_warehouse_vc5 = driver.find_element(By.XPATH,
                                           "//li[. = 'DT warehouse - VC']")
    dt_warehouse_vc5.click()

    # 23. Click 'Target Warehouse'
    target_warehouse = driver.find_element(By.XPATH,
                                           "//input[@placeholder = 'Target Warehouse']")
    target_warehouse.click()

    # 24. Click 'Work In Progress - VC3'
    work_in_progress_vc3 = driver.find_element(By.XPATH,
                                               "//div[3]/div[1]/div/div/div/ul//strong[. = 'Work In Progress - VC']")
    work_in_progress_vc3.click()

    # 25. Click 'Qty'
    qty = driver.find_element(By.XPATH,
                              "//input[@placeholder = 'Qty']")
    qty.click()

    # 26. Type '10.00' in 'Qty'
    qty = driver.find_element(By.XPATH,
                              "//input[@placeholder = 'Qty']")
    qty.send_keys("10.00")

    # 27. Click 'Item Code2'
    item_code2 = driver.find_element(By.XPATH,
                                     "//input[@placeholder = 'Item Code']")
    item_code2.click()

    # 28. Click 'Finished Oil, Dry Goods, Extracted Ja...1'
    finished_oil_dry_goods_extracted_ja_1 = driver.find_element(By.XPATH,
                                                                "//span[. = 'Finished Oil, Dry Goods, Extracted Jack Herer Cannabis Oil']")
    finished_oil_dry_goods_extracted_ja_1.click()

    # 29. Click 'Save1'
    save1 = driver.find_element(By.XPATH,
                                "//span[. = 'Save']")
    save1.click()

    # 30. Scroll window by ('0','-400')
    driver.execute_script("window.scrollBy(0,-400)")

    # 31. Does 'Saved11' contain 'Saved'?
    saved11 = driver.find_element(By.XPATH,
                                  "//div[. = 'Saved']")
    step_output = saved11.text
    assert step_output and ("Saved" in step_output)

    # 32. Click 'Stock Entry3'
    stock_entry3 = driver.find_element(By.XPATH,
                                       "//li[2]/a[. = 'Stock Entry']")
    stock_entry3.click()

    # 33. Click 'INPUT6'
    input6 = driver.find_element(By.XPATH,
                                 "//div[2]/div[2]/div[1]/div[1]/div/input")
    input6.click()

    # 34. Click 'SPAN'
    span = driver.find_element(By.XPATH,
                               "//div[3]/div[1]/div/div/div[2]/div[2]/button/span[1]")
    span.click()

    # 35. Click 'Edit1'
    edit1 = driver.find_element(By.XPATH,
                                "//a[. = '\n\t\t\t\tEdit']")
    edit1.click()

    # 36. Click 'SELECT11'
    select11 = driver.find_element(By.XPATH,
                                   "//div[2]/div[1]/div/div[2]/div/div/div/form//select")
    select11.click()

    # 37. Select the 'Stock Entry Type' option in 'SELECT12'
    select12 = driver.find_element(By.XPATH,
                                   "//div[2]/div[1]/div/div[2]/div/div/div/form//select")
    Select(select12).select_by_value("Stock Entry Type")

    # 38. Click 'SELECT12'
    select12 = driver.find_element(By.XPATH,
                                   "//div[2]/div[1]/div/div[2]/div/div/div/form//select")
    select12.click()

    # 39. Click 'INPUT49'
    input49 = driver.find_element(By.XPATH,
                                  "//div[2]/div[1]/div/div[2]/div/div/div/form//input")
    input49.click()

    # 40. Click 'Material Receipt'
    material_receipt = driver.find_element(By.XPATH,
                                           "//div[2]/div/div[2]//li[. = 'Material Receipt']")
    material_receipt.click()

    # 41. Click 'Update1'
    update1 = driver.find_element(By.XPATH,
                                  "//button[. = 'Update']")
    update1.click()

    # 42. Click 'Close1'
    close1 = driver.find_element(By.XPATH,
                                 "//div[2]/div/div//button[. = '\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\tClose\n\t\t\t\t\t\t\t\t']")
    close1.click()

    # 43. Click 'SPAN6'
    span6 = driver.find_element(By.XPATH,
                                "//div[3]/div[1]/div/div/div[2]/div[2]/button/span/span[2]")
    span6.click()

    # 44. Click 'Edit1'
    edit1 = driver.find_element(By.XPATH,
                                "//a[. = '\n\t\t\t\tEdit']")
    edit1.click()

    # 45. Click 'SELECT13'
    select13 = driver.find_element(By.XPATH,
                                   "//div[2]/div/div[2]/div[1]/div//select")
    select13.click()

    # 46. Select the 'Delivery Note No' option in 'SELECT13'
    select13 = driver.find_element(By.XPATH,
                                   "//div[2]/div/div[2]/div[1]/div//select")
    Select(select13).select_by_value("Delivery Note No")

    # 47. Click 'SELECT13'
    select13 = driver.find_element(By.XPATH,
                                   "//div[2]/div/div[2]/div[1]/div//select")
    select13.click()

    # 48. Click 'INPUT50'
    input50 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div[2]/div[1]/div/div[2]//input")
    input50.click()

    # 49. Click 'SELECT13'
    select13 = driver.find_element(By.XPATH,
                                   "//div[2]/div/div[2]/div[1]/div//select")
    select13.click()

    # 50. Select the 'Manufacturing Type' option in 'SELECT13'
    select13 = driver.find_element(By.XPATH,
                                   "//div[2]/div/div[2]/div[1]/div//select")
    Select(select13).select_by_value("Manufacturing Type")

    # 51. Click 'SELECT13'
    select13 = driver.find_element(By.XPATH,
                                   "//div[2]/div/div[2]/div[1]/div//select")
    select13.click()

    # 52. Click 'SELECT3'
    select3 = driver.find_element(By.XPATH,
                                  "//div[2]/div[1]/div/div[2]/div/div/div/form/div[2]//select")
    select3.click()

    # 53. Select the 'Process' option in 'SELECT3'
    select3 = driver.find_element(By.XPATH,
                                  "//div[2]/div[1]/div/div[2]/div/div/div/form/div[2]//select")
    Select(select3).select_by_value("Process")

    # 54. Click 'SELECT3'
    select3 = driver.find_element(By.XPATH,
                                  "//div[2]/div[1]/div/div[2]/div/div/div/form/div[2]//select")
    select3.click()

    # 55. Click 'Update2'
    update2 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div//button[. = 'Update']")
    update2.click()

    # 56. Does 'Updated successfully6' contain 'Updated successfully'?
    updated_successfully6 = driver.find_element(By.XPATH,
                                                "//div[. = 'Updated successfully']")
    step_output = updated_successfully6.text
    assert step_output and ("Updated successfully" in step_output)

    # 57. Click 'Settings'
    settings = driver.find_element(By.XPATH,
                                   "//span[. = '      Settings']")
    settings.click()

    # 58. Click 'Logout'
    logout = driver.find_element(By.XPATH,
                                 "//a[. = '       Logout']")
    logout.click()
