from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Bloomy_Core
    Package: TestProject.Generated.Tests.BloomyCore
    Test: CreateChartOf Account_Testcaes01
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 04/12/2021, 11:28:24
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Bloomy_Core",
                              job_name="CreateChartOf Account_Testcaes01")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("rahul.prakash@extrapreneursindia.com")

    # 5. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 6. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 7. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 8. Click 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.click()

    # 9. Type 'chart' in 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.send_keys("chart")

    # 10. Click 'Open Chart of Accounts'
    open_chart_of_accounts = driver.find_element(By.XPATH,
                                                 "//li[. = 'Open Chart of Accounts']")
    open_chart_of_accounts.click()

    # 11. Does 'Chart Of Accounts' contain 'Chart Of Accounts'?
    chart_of_accounts = driver.find_element(By.XPATH,
                                            "//div[. = 'Chart Of Accounts']")
    step_output = chart_of_accounts.text
    assert step_output and ("Chart Of Accounts" in step_output)

    # 12. Click 'Company'
    company = driver.find_element(By.XPATH,
                                  "//select[@placeholder = 'Company']")
    company.click()

    # 13. Select the 'EPI- Extrapreneurs India Pvt Ltd.' option in 'Company'
    company = driver.find_element(By.XPATH,
                                  "//select[@placeholder = 'Company']")
    Select(company).select_by_value("EPI- Extrapreneurs India Pvt Ltd.")

    # 14. Click 'Company'
    company = driver.find_element(By.XPATH,
                                  "//select[@placeholder = 'Company']")
    company.click()

    # 15. Does 'SPAN3' contain '[NONE]'?
    span3 = driver.find_element(By.XPATH,
                                "//div[3]/span[1]")
    step_output = span3.text
    assert step_output and ("" in step_output)

    # 16. Click 'New'
    new = driver.find_element(By.XPATH,
                              "//span[. = 'New']")
    new.click()

    # 17. Type 'EPI Rahul Sinha' in 'INPUT32'
    input32 = driver.find_element(By.XPATH,
                                  "//div[1]/div/div[2]/div[1]/input")
    input32.send_keys("EPI Rahul Sinha")

    # 18. Click 'INPUT33'
    input33 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div[2]/div/input")
    input33.click()

    # 19. Type '2768987687' in 'INPUT33'
    input33 = driver.find_element(By.XPATH,
                                  "//div[2]/div/div[2]/div/input")
    input33.send_keys("2768987687")

    # 20. Click 'SELECT7'
    select7 = driver.find_element(By.XPATH,
                                  "//div[5]//select")
    select7.click()

    # 21. Select the 'Bank' option in 'SELECT7'
    select7 = driver.find_element(By.XPATH,
                                  "//div[5]//select")
    Select(select7).select_by_value("Bank")

    # 22. Click 'SELECT7'
    select7 = driver.find_element(By.XPATH,
                                  "//div[5]//select")
    select7.click()

    # 23. Click 'INPUT34'
    input34 = driver.find_element(By.XPATH,
                                  "//span/input")
    input34.click()

    # 24. Click 'SELECT8'
    select8 = driver.find_element(By.XPATH,
                                  "//div[4]/div/div[2]//select")
    select8.click()

    # 25. Select the 'Asset' option in 'SELECT8'
    select8 = driver.find_element(By.XPATH,
                                  "//div[4]/div/div[2]//select")
    Select(select8).select_by_value("Asset")

    # 26. Click 'SELECT8'
    select8 = driver.find_element(By.XPATH,
                                  "//div[4]/div/div[2]//select")
    select8.click()

    # 27. Click 'INPUT35'
    input35 = driver.find_element(By.XPATH,
                                  "//div/div[2]/div[1]/div/div/input")
    input35.click()

    # 28. Click 'USD'
    usd = driver.find_element(By.XPATH,
                              "//p[. = 'USD']")
    usd.click()

    # 29. Does 'New Account' contain 'New Account'?
    new_account = driver.find_element(By.XPATH,
                                      "//h4[. = 'New Account']")
    step_output = new_account.text
    assert step_output and ("New Account" in step_output)

    # 30. Click 'Create New'
    create_new = driver.find_element(By.XPATH,
                                     "//button[. = 'Create New']")
    create_new.click()

    # 31. Click '2768987687 - EPI Rahul Sinha - EPI-EI...'
    _2768987687_epi_rahul_sinha_epi_ei_ = driver.find_element(By.XPATH,
                                                              "//a[. = ' 2768987687 - EPI Rahul Sinha - EPI-EIPL']")
    _2768987687_epi_rahul_sinha_epi_ei_.click()

    # 32. Click '2768987687 - EPI Rahul Sinha - EPI-EI...'
    _2768987687_epi_rahul_sinha_epi_ei_ = driver.find_element(By.XPATH,
                                                              "//a[. = ' 2768987687 - EPI Rahul Sinha - EPI-EIPL']")
    _2768987687_epi_rahul_sinha_epi_ei_.click()

    # 33. Click '2768987687 - EPI Rahul Sinha - EPI-EI...'
    _2768987687_epi_rahul_sinha_epi_ei_ = driver.find_element(By.XPATH,
                                                              "//a[. = ' 2768987687 - EPI Rahul Sinha - EPI-EIPL']")
    _2768987687_epi_rahul_sinha_epi_ei_.click()

    # 34. Click 'Settings1'
    settings1 = driver.find_element(By.XPATH,
                                    "//span[. = '      Settings']")
    settings1.click()

    # 35. Click 'Logout'
    logout = driver.find_element(By.XPATH,
                                 "//a[. = '       Logout']")
    logout.click()
