import time

from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest

"""
This pytest test was automatically generated by TestProject
    Project: Demo_ Bloomy
    Package: TestProject.Generated.Tests.DemoBloomy
    Test: CreateMaterialRequest_TestCase02
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 03/08/2021, 10:40:40
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Demo_ Bloomy",
                              job_name="CreateMaterialRequest_TestCase02")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("rahul.prakash@extrapreneursindia.com")

    # 5. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 6. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 7. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 8. Click 'Purchasing'
    purchasing = driver.find_element(By.XPATH,
                                     "//div[. = '\n                Purchasing\n              ']")
    purchasing.click()

    # 9. Does 'Purchasing2' contain 'Purchasing'?
    purchasing2 = driver.find_element(By.XPATH,
                                      "//div[. = 'Purchasing']")
    step_output = purchasing2.text
    assert step_output and ("Purchasing" in step_output)

    # 10. Click 'Material Request'
    material_request = driver.find_element(By.XPATH,
                                           "//div/a[. = 'Material Request']")
    material_request.click()

    # 11. Does 'Material Request2' contain 'Material Request'?
    material_request2 = driver.find_element(By.XPATH,
                                            "//div[. = 'Material Request']")
    step_output = material_request2.text
    assert step_output and ("Material Request" in step_output)
    time.sleep(3)

    # 12. Click 'New'
    new = driver.find_element(By.XPATH,
                              "//span[. = 'New']")
    new.click()
    time.sleep(3)

    # 13. Click 'INPUT12'
    input12 = driver.find_element(By.XPATH,
                                  "//div[2]/form/div[2]//input")
    input12.click()

    # 14. Type 'extra' in 'INPUT12'
    input12 = driver.find_element(By.XPATH,
                                  "//div[2]/form/div[2]//input")
    input12.send_keys("extra")
    time.sleep(2)

    # 15. Click 'Extrapreneurs India Pvt Ltd1'
    extrapreneurs_india_pvt_ltd1 = driver.find_element(By.XPATH,
                                                       "//strong[. = 'Extrapreneurs India Pvt Ltd']")
    extrapreneurs_india_pvt_ltd1.click()

    # 16. Click 'INPUT11'
    input11 = driver.find_element(By.XPATH,
                                  "//div[2]/form/div[1]//input")
    input11.click()

    # 17. Click '291'
    _291 = driver.find_element(By.XPATH,
                               "//div[1]/div[1]/div/div/div[. = '29']")
    _291.click()

    # 18. Scroll window by ('0','200')
    driver.execute_script("window.scrollBy(0,200)")

    # 19. Click 'DIV'
    div = driver.find_element(By.XPATH,
                              "//div[2]/div/div[2]/div[2]/div[1]/div/div/div[2]")
    div.click()

    # 20. Type 'epi' in 'Item Code'
    item_code = driver.find_element(By.XPATH,
                                    "//input[@placeholder = 'Item Code']")
    item_code.send_keys("epi")

    # 21. Click 'P31'
    p31 = driver.find_element(By.XPATH,
                              "//div[1]/div/div/div/ul/li[2]//p")
    p31.click()

    # 22. Click 'For Warehouse'
    for_warehouse = driver.find_element(By.XPATH,
                                        "//input[@placeholder = 'For Warehouse']")
    for_warehouse.click()

    # 23. Click 'EPI-Warehouse2 - EIPL'
    epi_warehouse2_eipl = driver.find_element(By.XPATH,
                                              "//strong[. = 'EPI-Warehouse2 - EIPL']")
    epi_warehouse2_eipl.click()

    # 24. Click 'Save'
    save = driver.find_element(By.XPATH,
                               "//span[. = 'Save']")
    save.click()

    # 25. Scroll window by ('0','-200')
    driver.execute_script("window.scrollBy(0,-200)")

    # 26. Does 'Saved9' contain 'Saved'?
    saved9 = driver.find_element(By.XPATH,
                                 "//div[. = 'Saved']")
    step_output = saved9.text
    assert step_output and ("Saved" in step_output)

    # 27. Does 'Purchase Request for EPI-Tshirt-L-WHI' contain 'Purchase Request for EPI-Tshirt-L-WHI'?
    purchase_request_for_epi_tshirt_l_whi = driver.find_element(By.XPATH,
                                                                "//div[. = 'Purchase Request for EPI-Tshirt-L-WHI']")
    step_output = purchase_request_for_epi_tshirt_l_whi.text
    assert step_output and (
            "Purchase Request for EPI-Tshirt-L-WHI" in step_output)

    # 28. Click 'Submit'
    submit = driver.find_element(By.XPATH,
                                 "//button/span[. = 'Submit']")
    submit.click()

    # 29. Click 'Yes'
    yes = driver.find_element(By.XPATH,
                              "//button[. = 'Yes']")
    yes.click()

    # 30. Does 'Saved11' contain 'Saved'?
    saved11 = driver.find_element(By.XPATH,
                                  "//div[2]/div[. = 'Saved']")
    step_output = saved11.text
    assert step_output and ("Saved" in step_output)
