import time

from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Demo_ Bloomy
    Package: TestProject.Generated.Tests.DemoBloomy
    Test: DeletePackageTag_TestCase01
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 03/25/2021, 07:22:36
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Demo_ Bloomy",
                              job_name="DeletePackageTag_TestCase01")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"
    GridValue = "Does 20 of 760 Generic Web Element contain \"20 of 760\" ?"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("rahul.prakash@extrapreneursindia.com")

    # 5. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 6. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 7. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 8. Click 'Stock5'
    stock5 = driver.find_element(By.XPATH,
                                 "//div[. = '\n                Stock\n              ']")
    stock5.click()

    # 9. Does 'Stock1' contain 'Stock'?
    stock1 = driver.find_element(By.XPATH,
                                 "//div[. = 'Stock']")
    step_output = stock1.text
    assert step_output and ("Stock" in step_output)

    # 10. Click 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.click()

    # 11. Type 'package' in 'Search or type a command (Ctrl + G)'
    search_or_type_a_command_ctrl_g_ = driver.find_element(By.CSS_SELECTOR,
                                                           "#navbar-search")
    search_or_type_a_command_ctrl_g_.send_keys("package")

    # 12. Click 'New Package Tag'
    new_package_tag = driver.find_element(By.XPATH,
                                          "//li[. = 'New Package Tag']")
    new_package_tag.click()

    # 13. Click 'INPUT59'
    input59 = driver.find_element(By.XPATH,
                                  "//div[1]/div/div[2]/div[1]/div/div/input")
    input59.click()

    # 14. Type 'extra' in 'INPUT59'
    input59 = driver.find_element(By.XPATH,
                                  "//div[1]/div/div[2]/div[1]/div/div/input")
    input59.send_keys("extra")

    # 15. Click 'Extrapreneurs India Pvt Ltd10'
    extrapreneurs_india_pvt_ltd10 = driver.find_element(By.XPATH,
                                                        "//li[. = 'Extrapreneurs India Pvt Ltd']")
    extrapreneurs_india_pvt_ltd10.click()

    # 16. Click 'INPUT60'
    input60 = driver.find_element(By.XPATH,
                                  "//div[2]/div/input")
    input60.click()

    # 17. Type 'Delete Package' in 'INPUT60'
    input60 = driver.find_element(By.XPATH,
                                  "//div[2]/div/input")
    input60.send_keys("Delete Package")

    # 18. Click 'INPUT62'
    input62 = driver.find_element(By.XPATH,
                                  "//div[3]/div/div[2]//input")
    input62.click()

    # 19. Click 'P9'
    p9 = driver.find_element(By.XPATH,
                             "//div[3]/div/div[2]/div[1]/div/div/ul/li[2]//p[1]")
    p9.click()

    # 20. Does 'New Package Tag1' contain 'New Package Tag'?
    new_package_tag1 = driver.find_element(By.XPATH,
                                           "//h4[. = 'New Package Tag']")
    step_output = new_package_tag1.text
    assert step_output and ("New Package Tag" in step_output)

    # 21. Click 'Edit in full page'
    edit_in_full_page = driver.find_element(By.XPATH,
                                            "//button[. = 'Edit in full page']")
    edit_in_full_page.click()
    time.sleep(2)

    # 22. Click 'Save3'
    save3 = driver.find_element(By.XPATH,
                                "//span[. = 'Save']")
    save3.click()

    # 23. Does 'Saved11' contain 'Saved'?
    saved11 = driver.find_element(By.XPATH,
                                  "//div[. = 'Saved']")
    step_output = saved11.text
    assert step_output and ("Saved" in step_output)

    # 24. Click 'Package Tag'
    package_tag = driver.find_element(By.XPATH,
                                      "//a[. = 'Package Tag']")
    package_tag.click()
    time.sleep(2)

    # 25. Click 'INPUT14'
    input14 = driver.find_element(By.XPATH,
                                  "//*[@id='page-List/Package Tag/List']/div[2]/div[2]/div/div[3]/div[2]/div[1]/div["
                                  "3]/div[2]/div[2]/div[1]/div[1]/div[1]/input")
    input14.click()

    # 26. Click 'Actions2'
    actions2 = driver.find_element(By.XPATH,
                                   "//div[4]//span[. = 'Actions']")
    actions2.click()

    # 27. Click 'Delete4'
    delete4 = driver.find_element(By.XPATH,
                                  "//a[. = '\n\t\t\t\tDelete']")
    delete4.click()

    # 28. Click 'Yes'
    yes = driver.find_element(By.XPATH,
                              "//button[. = 'Yes']")
    yes.click()

    # 29. Does '20 of 760' contain '{GridValue}'?
    if float(f'{GridValue}') <= float("Does 20 of 760 Generic Web Element contain \"20 of 760\" ?\r\n\r\n\r\n"):
        _20_of_760 = driver.find_element(By.XPATH,
                                         "//span/span[. = '20 of 760']")
        step_output = _20_of_760.text
        assert step_output and (f'{GridValue}' in step_output)

    # 30. Click 'Settings'
    settings = driver.find_element(By.XPATH,
                                   "//span[. = '      Settings']")
    settings.click()

    # 31. Click 'Logout'
    logout = driver.find_element(By.XPATH,
                                 "//a[. = '       Logout']")
    logout.click()
