import time

from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Demo_ Bloomy
    Package: TestProject.Generated.Tests.DemoBloomy
    Test: CreatePackingSlip_TestCase
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 03/22/2021, 06:02:21
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Demo_ Bloomy",
                              job_name="CreatePackingSlip_TestCase")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("rahul.prakash@extrapreneursindia.com")

    # 5. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 6. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 7. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 8. Click 'Stock'
    stock = driver.find_element(By.XPATH,
                                "//div[. = '\n                Stock\n              ']")
    stock.click()

    # 9. Does 'Stock1' contain 'Stock'?
    stock1 = driver.find_element(By.XPATH,
                                 "//div[. = 'Stock']")
    step_output = stock1.text
    assert step_output and ("Stock" in step_output)

    # 10. Click 'Delivery Note'
    delivery_note = driver.find_element(By.XPATH,
                                        "//div/a[. = 'Delivery Note']")
    delivery_note.click()

    # 11. Does 'Delivery Note1' contain 'Delivery Note'?
    delivery_note1 = driver.find_element(By.XPATH,
                                         "//div[. = 'Delivery Note']")
    step_output = delivery_note1.text
    assert step_output and ("Delivery Note" in step_output)
    time.sleep(3)

    # 12. Click 'New1'
    new1 = driver.find_element(By.XPATH,
                               "//span[. = 'New']")
    new1.click()

    # 13. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//div[2]/form/div[2]/div/div[2]/div[1]/div//input")
    input.click()

    # 14. Type 'vap' in 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//div[2]/form/div[2]/div/div[2]/div[1]/div//input")
    input.send_keys("vap")

    # 15. Click 'VapeCo'
    vapeco = driver.find_element(By.XPATH,
                                 "//strong[. = 'VapeCo']")
    vapeco.click()

    # 16. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//div[3]/div[2]/div[1]/form//input")
    input1.click()

    # 17. Click 'LI2'
    li2 = driver.find_element(By.XPATH,
                              "//div[3]/div/div[2]/div[1]/div/div/ul/li[1]")
    li2.click()

    # 18. Scroll window by ('0','300')
    driver.execute_script("window.scrollBy(0,300)")

    # 19. Scroll window by ('0','199')
    driver.execute_script("window.scrollBy(0,199)")

    # 20. Scroll window by ('0','199')
    driver.execute_script("window.scrollBy(0,199)")

    # 21. Click 'DIV'
    div = driver.find_element(By.XPATH,
                              "//div[2]/div/div[2]/div[2]/div[1]/div/div/div[2]")
    div.click()

    # 22. Click 'P7'
    p7 = driver.find_element(By.XPATH,
                             "//div[1]/div/div/div/ul/li[2]/a/p")
    p7.click()

    # 23. Does 'Select Serial Numbers1' contain 'Select Serial Numbers'?
    select_serial_numbers1 = driver.find_element(By.XPATH,
                                                 "//h4[. = 'Select Serial Numbers']")
    step_output = select_serial_numbers1.text
    assert step_output and ("Select Serial Numbers" in step_output)

    # 24. Click 'Insert'
    insert = driver.find_element(By.XPATH,
                                 "//button[. = 'Insert']")
    insert.click()

    # 25. Click 'Save1'
    save1 = driver.find_element(By.XPATH,
                                "//span[. = 'Save']")
    save1.click()

    # 26. Scroll window by ('0','-699')
    driver.execute_script("window.scrollBy(0,-699)")

    # 27. Click 'Close'
    close = driver.find_element(By.XPATH,
                                "//div[2]/div/div//span[. = 'Close']")
    close.click()

    # 28. Does 'Saved' contain 'Saved'?
    saved = driver.find_element(By.XPATH,
                                "//div[. = 'Saved']")
    step_output = saved.text
    assert step_output and ("Saved" in step_output)

    # 29. Does 'DIV1' contain '[NONE]'?
    div1 = driver.find_element(By.XPATH,
                               "//div[4]/div[1]/div/div/div[1]/h1/div[2]")
    step_output = div1.text
    assert step_output and ("" in step_output)

    # 30. Click 'I'
    i = driver.find_element(By.XPATH,
                            "//div[5]/div/div/div[1]/div[1]/div[2]/button/i")
    i.click()

    # 31. Scroll window by ('0','300')
    driver.execute_script("window.scrollBy(0,300)")

    # 32. Scroll window by ('0','-200')
    driver.execute_script("window.scrollBy(0,-200)")

    # 33. Click 'INPUT27'
    input27 = driver.find_element(By.XPATH,
                                  "//div[5]/div/div[1]/form/div[1]//input")
    input27.click()

    # 34. Click 'DT warehouse - VC2'
    dt_warehouse_vc2 = driver.find_element(By.XPATH,
                                           "//li[. = 'DT warehouse - VC']")
    dt_warehouse_vc2.click()

    # 35. Scroll window by ('0','200')
    driver.execute_script("window.scrollBy(0,200)")

    # 36. Scroll window by ('0','200')
    driver.execute_script("window.scrollBy(0,200)")

    # 37. Scroll window by ('0','135')
    driver.execute_script("window.scrollBy(0,135)")

    # 38. Scroll window by ('0','-299')
    driver.execute_script("window.scrollBy(0,-299)")

    # 39. Scroll window by ('0','-100')
    driver.execute_script("window.scrollBy(0,-100)")

    # 40. Click 'Save9'
    save9 = driver.find_element(By.XPATH,
                                "//span[. = 'Save']")
    save9.click()

    # 41. Scroll window by ('0','-235')
    driver.execute_script("window.scrollBy(0,-235)")

    # 42. Does 'DIV9' contain '[NONE]'?
    div9 = driver.find_element(By.XPATH,
                               "//div[5]/div[1]/div/div/div[1]/h1/div[2]")
    step_output = div9.text
    assert step_output and ("" in step_output)

    # 43. Does 'Saved1' contain 'Saved'?
    saved1 = driver.find_element(By.XPATH,
                                 "//div[2]/div[. = 'Saved']")
    step_output = saved1.text
    assert step_output and ("Saved" in step_output)

    # 44. Click 'Submit5'
    submit5 = driver.find_element(By.XPATH,
                                  "//div[5]//span[. = 'Submit']")
    submit5.click()

    # 45. Click 'Yes'
    yes = driver.find_element(By.XPATH,
                              "//button[. = 'Yes']")
    yes.click()

    # 46. Does 'Saved4' contain 'Saved'?
    saved4 = driver.find_element(By.XPATH,
                                 "//div[3]/div[. = 'Saved']")
    step_output = saved4.text
    assert step_output and ("Saved" in step_output)

    # 47. Does 'Submitted1' contain 'Submitted'?
    submitted1 = driver.find_element(By.XPATH,
                                     "//div/span[. = 'Submitted']")
    step_output = submitted1.text
    assert step_output and ("Submitted" in step_output)

    # 48. Scroll window by ('0','300')
    driver.execute_script("window.scrollBy(0,300)")

    # 49. Scroll window by ('0','-300')
    driver.execute_script("window.scrollBy(0,-300)")

    # 50. Click 'Settings'
    settings = driver.find_element(By.XPATH,
                                   "//span[. = '      Settings']")
    settings.click()

    # 51. Click 'Logout'
    logout = driver.find_element(By.XPATH,
                                 "//a[. = '       Logout']")
    logout.click()
