from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Demo_ Bloomy
    Package: TestProject.Generated.Tests.DemoBloomy
    Test: UpdateDeliveryNote_TestCase02
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 03/18/2021, 05:26:56
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Demo_ Bloomy",
                              job_name="UpdateDeliveryNote_TestCase02")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("rahul.prakash@extrapreneursindia.com")

    # 5. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 6. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 7. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 8. Click 'Stock'
    stock = driver.find_element(By.XPATH,
                                "//div[. = '\n                Stock\n              ']")
    stock.click()

    # 9. Does 'Stock1' contain 'Stock'?
    stock1 = driver.find_element(By.XPATH,
                                 "//div[. = 'Stock']")
    step_output = stock1.text
    assert step_output and ("Stock" in step_output)

    # 10. Click 'Delivery Note'
    delivery_note = driver.find_element(By.XPATH,
                                        "//div/a[. = 'Delivery Note']")
    delivery_note.click()

    # 11. Does 'Delivery Note1' contain 'Delivery Note'?
    delivery_note1 = driver.find_element(By.XPATH,
                                         "//div[. = 'Delivery Note']")
    step_output = delivery_note1.text
    assert step_output and ("Delivery Note" in step_output)

    # 12. Click 'New1'
    new1 = driver.find_element(By.XPATH,
                               "//span[. = 'New']")
    new1.click()

    # 13. Does 'DIV1' contain '[NONE]'?
    div1 = driver.find_element(By.XPATH,
                               "//div[4]/div[1]/div/div/div[1]/h1/div[2]")
    step_output = div1.text
    assert step_output and ("" in step_output)

    # 14. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//div[2]/form/div[2]/div/div[2]/div[1]/div//input")
    input.click()

    # 15. Type 'vap' in 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//div[2]/form/div[2]/div/div[2]/div[1]/div//input")
    input.send_keys("vap")

    # 16. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//div[2]/form/div[2]/div/div[2]/div[1]/div//input")
    input.click()

    # 17. Type 'vap' in 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//div[2]/form/div[2]/div/div[2]/div[1]/div//input")
    input.send_keys("vap")

    # 18. Click 'VapeCo'
    vapeco = driver.find_element(By.XPATH,
                                 "//strong[. = 'VapeCo']")
    vapeco.click()

    # 19. Click 'Date'
    date = driver.find_element(By.XPATH,
                               "//div[. = '\t\t\t\t\t\tDate\t\t\t\t\t']")
    date.click()

    # 20. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//div[3]/div[2]/div[1]/form//input")
    input1.click()

    # 21. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//div[3]/div[2]/div[1]/form//input")
    input1.click()

    # 22. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//div[3]/div[2]/div[1]/form//input")
    input1.click()

    # 23. Click 'P'
    p = driver.find_element(By.XPATH,
                            "//div[3]/div/div[2]/div[1]/div/div/ul/li[1]//p")
    p.click()

    # 24. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 25. Scroll window by ('0','300')
    driver.execute_script("window.scrollBy(0,300)")

    # 26. Scroll window by ('0','400')
    driver.execute_script("window.scrollBy(0,400)")

    # 27. Scroll window by ('0','300')
    driver.execute_script("window.scrollBy(0,300)")

    # 28. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 29. Scroll window by ('0','300')
    driver.execute_script("window.scrollBy(0,300)")

    # 30. Scroll window by ('0','-200')
    driver.execute_script("window.scrollBy(0,-200)")

    # 31. Scroll window by ('0','-200')
    driver.execute_script("window.scrollBy(0,-200)")

    # 32. Scroll window by ('0','-200')
    driver.execute_script("window.scrollBy(0,-200)")

    # 33. Scroll window by ('0','-200')
    driver.execute_script("window.scrollBy(0,-200)")

    # 34. Scroll window by ('0','-100')
    driver.execute_script("window.scrollBy(0,-100)")

    # 35. Scroll window by ('0','-500')
    driver.execute_script("window.scrollBy(0,-500)")

    # 36. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 37. Scroll window by ('0','200')
    driver.execute_script("window.scrollBy(0,200)")

    # 38. Click 'DIV'
    div = driver.find_element(By.XPATH,
                              "//div[2]/div/div[2]/div[2]/div[1]/div/div/div[2]")
    div.click()

    # 39. Click 'Item Code1'
    item_code1 = driver.find_element(By.XPATH,
                                     "//input[@placeholder = 'Item Code']")
    item_code1.click()

    # 40. Click 'VC-RM-FO-0001'
    vc_rm_fo_0001 = driver.find_element(By.XPATH,
                                        "//strong[. = 'VC-RM-FO-0001']")
    vc_rm_fo_0001.click()

    # 41. Click 'Insert'
    insert = driver.find_element(By.XPATH,
                                 "//button[. = 'Insert']")
    insert.click()

    # 42. Click 'Save1'
    save1 = driver.find_element(By.XPATH,
                                "//span[. = 'Save']")
    save1.click()

    # 43. Scroll window by ('0','-400')
    driver.execute_script("window.scrollBy(0,-400)")

    # 44. Click 'Close1'
    close1 = driver.find_element(By.XPATH,
                                 "//div[2]/div/div//button[. = '\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\tClose\n\t\t\t\t\t\t\t\t']")
    close1.click()

    # 45. Does 'DIV1' contain '[NONE]'?
    div1 = driver.find_element(By.XPATH,
                               "//div[4]/div[1]/div/div/div[1]/h1/div[2]")
    step_output = div1.text
    assert step_output and ("" in step_output)

    # 46. Click 'Delivery Note3'
    delivery_note3 = driver.find_element(By.XPATH,
                                         "//div[1]/ul//a[. = 'Delivery Note']")
    delivery_note3.click()

    # 47. Click 'INPUT6'
    input6 = driver.find_element(By.XPATH,
                                 "//div[2]/div[2]/div[1]/div[1]/div/input")
    input6.click()

    # 48. Click 'SPAN'
    span = driver.find_element(By.XPATH,
                               "//div[3]/div[1]/div/div/div[2]/div[2]/button/span[1]")
    span.click()

    # 49. Click 'Edit'
    edit = driver.find_element(By.XPATH,
                               "//a[. = '\n\t\t\t\tEdit']")
    edit.click()

    # 50. Click 'SELECT'
    select = driver.find_element(By.XPATH,
                                 "//div[2]/div[1]/div/div[2]/div/div/div/form//select")
    select.click()

    # 51. Select the 'Edit Posting Date and Time' option in 'SELECT'
    select = driver.find_element(By.XPATH,
                                 "//div[2]/div[1]/div/div[2]/div/div/div/form//select")
    Select(select).select_by_value("Edit Posting Date and Time")

    # 52. Click 'SELECT'
    select = driver.find_element(By.XPATH,
                                 "//div[2]/div[1]/div/div[2]/div/div/div/form//select")
    select.click()

    # 53. Click 'INPUT7'
    input7 = driver.find_element(By.XPATH,
                                 "//div[2]/div[1]/div/div[2]/div/div/div/form/div[2]/div/label//input")
    input7.click()

    # 54. Is 'INPUT7' visible and selected?
    input7 = driver.find_element(By.XPATH,
                                 "//div[2]/div[1]/div/div[2]/div/div/div/form/div[2]/div/label//input")
    assert input7.is_selected()

    # 55. Click 'Update'
    update = driver.find_element(By.XPATH,
                                 "//button[. = 'Update']")
    update.click()

    # 56. Click 'Close'
    close = driver.find_element(By.XPATH,
                                "//div[2]/div/div//span[. = 'Close']")
    close.click()

    # 57. Does 'Updated successfully' contain 'Updated successfully'?
    updated_successfully = driver.find_element(By.XPATH,
                                               "//div[. = 'Updated successfully']")
    step_output = updated_successfully.text
    assert step_output and ("Updated successfully" in step_output)

    # 58. Click 'Airfield Supply Co.'
    airfield_supply_co_ = driver.find_element(By.XPATH,
                                              "//div[2]/div/div[1]/div[1]/span/a[. = '\n\t\t\t\tAirfield Supply Co.\n\t\t\t\t']")
    airfield_supply_co_.click()

    # 59. Click 'Submit'
    submit = driver.find_element(By.XPATH,
                                 "//button/span[. = 'Submit']")
    submit.click()

    # 60. Click 'Yes'
    yes = driver.find_element(By.XPATH,
                              "//button[. = 'Yes']")
    yes.click()

    # 61. Click 'Close'
    close = driver.find_element(By.XPATH,
                                "//div[2]/div/div//span[. = 'Close']")
    close.click()

    # 62. Click 'DIV2'
    div2 = driver.find_element(By.XPATH,
                               "//body/div[1]/div/div[4]/div[1]/div/div/div[2]")
    div2.click()

    # 63. Does 'To Deliver' contain 'To Deliver'?
    to_deliver = driver.find_element(By.XPATH,
                                     "//div/span[. = 'To Deliver']")
    step_output = to_deliver.text
    assert step_output and ("To Deliver" in step_output)

    # 64. Click 'Settings'
    settings = driver.find_element(By.XPATH,
                                   "//span[. = '      Settings']")
    settings.click()

    # 65. Click 'Logout'
    logout = driver.find_element(By.XPATH,
                                 "//a[. = '       Logout']")
    logout.click()
