import time

from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Demo_ Bloomy
    Package: TestProject.Generated.Tests.DemoBloomy
    Test: MaterialRequest_TestCase02
    Generated by: Rahul Prakash (rahulprakash0862@gmail.com)
    Generated on 03/08/2021, 10:40:25
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="5o-UXmLZug6gaKmDcoeI6tT7NM19XyG1qnolFybLul4",
                              project_name="Demo_ Bloomy",
                              job_name="MaterialRequest_TestCase02")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://epitest-demo.bloomstack.io/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//a[. = 'Login']")
    login.click()

    # 3. Click 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.click()

    # 4. Type 'rahul.prakash@extrapreneursindia.com' in 'Email Address'
    email_address = driver.find_element(By.CSS_SELECTOR,
                                        "#login_email")
    email_address.send_keys("rahul.prakash@extrapreneursindia.com")

    # 5. Click 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.click()

    # 6. Type 'epi@123' in 'Password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#login_password")
    password.send_keys("epi@123")

    # 7. Click 'Login1'
    login1 = driver.find_element(By.XPATH,
                                 "//button[. = '\n\t\t\t\tLogin']")
    login1.click()

    # 8. Click 'Purchasing'
    purchasing = driver.find_element(By.XPATH,
                                     "//div[. = '\n                Purchasing\n              ']")
    purchasing.click()

    # 9. Does 'Purchasing1' contain 'Purchasing'?
    purchasing1 = driver.find_element(By.XPATH,
                                      "//div[. = 'Purchasing']")
    step_output = purchasing1.text
    assert step_output and ("Purchasing" in step_output)

    # 10. Click 'Material Request'
    material_request = driver.find_element(By.XPATH,
                                           "//div/a[. = 'Material Request']")
    material_request.click()

    # 11. Does 'Material Request2' contain 'Material Request'?
    material_request2 = driver.find_element(By.XPATH,
                                            "//div[. = 'Material Request']")
    step_output = material_request2.text
    assert step_output and ("Material Request" in step_output)
    time.sleep(3)

    # 12. Click 'New'
    new = driver.find_element(By.XPATH,
                              "//span[. = 'New']")
    new.click()

    # 13. Click 'INPUT12'
    input12 = driver.find_element(By.XPATH,
                                  "//div[2]/form/div[2]//input")
    input12.click()

    # 14. Type 'extra' in 'INPUT12'
    input12 = driver.find_element(By.XPATH,
                                  "//div[2]/form/div[2]//input")
    input12.send_keys("extra")

    # 15. Click 'Extrapreneurs India Pvt Ltd1'
    extrapreneurs_india_pvt_ltd1 = driver.find_element(By.XPATH,
                                                       "//strong[. = 'Extrapreneurs India Pvt Ltd']")
    extrapreneurs_india_pvt_ltd1.click()

    # 16. Click 'INPUT11'
    input11 = driver.find_element(By.XPATH,
                                  "//div[2]/form/div[1]//input")
    input11.click()

    # 17. Click '311'
    _311 = driver.find_element(By.XPATH,
                               "//div[1]/div[1]/div/div/div[. = '31']")
    _311.click()

    # 18. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 19. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 20. Click 'DIV'
    div = driver.find_element(By.XPATH,
                              "//div[2]/div/div[2]/div[2]/div[1]/div/div/div[2]")
    div.click()

    # 21. Type 'epi' in 'Item Code'
    item_code = driver.find_element(By.XPATH,
                                    "//input[@placeholder = 'Item Code']")
    item_code.send_keys("epi")

    # 22. Click 'P30'
    p30 = driver.find_element(By.XPATH,
                              "//div[1]/div/div/div/ul/li[1]/a/p[1]")
    p30.click()

    # 23. Click 'For Warehouse'
    for_warehouse = driver.find_element(By.XPATH,
                                        "//input[@placeholder = 'For Warehouse']")
    for_warehouse.click()

    # 24. Click 'EPI-Warehouse2 - EIPL'
    epi_warehouse2_eipl = driver.find_element(By.XPATH,
                                              "//strong[. = 'EPI-Warehouse2 - EIPL']")
    epi_warehouse2_eipl.click()

    # 25. Scroll window by ('0','-200')
    driver.execute_script("window.scrollBy(0,-200)")

    # 26. Click 'Save'
    save = driver.find_element(By.XPATH,
                               "//span[. = 'Save']")
    save.click()

    # 27. Does 'Saved12' contain 'Saved'?
    saved12 = driver.find_element(By.XPATH,
                                  "//div[. = 'Saved']")
    step_output = saved12.text
    assert step_output and ("Saved" in step_output)

    # 28. Click 'Material Request3'
    material_request3 = driver.find_element(By.XPATH,
                                            "//li[2]/a[. = 'Material Request']")
    material_request3.click()

    # 29. Click 'INPUT40'
    input40 = driver.find_element(By.XPATH,
                                  "//div[2]/div[2]/div[1]/div[1]/div/input")
    input40.click()

    # 30. Click 'Actions'
    actions = driver.find_element(By.XPATH,
                                  "//div[3]//button[. = '               Actions                            ']")
    actions.click()

    # 31. Click 'Edit'
    edit = driver.find_element(By.XPATH,
                               "//a[. = '\n\t\t\t\tEdit']")
    edit.click()

    # 32. Click 'SELECT11'
    select11 = driver.find_element(By.XPATH,
                                   "//div[2]/div[1]/div/div[2]/div/div/div/form//select")
    select11.click()

    # 33. Select the 'Request For' option in 'SELECT11'
    select11 = driver.find_element(By.XPATH,
                                   "//div[2]/div[1]/div/div[2]/div/div/div/form//select")
    Select(select11).select_by_value("Request For")

    # 34. Click 'SELECT11'
    select11 = driver.find_element(By.XPATH,
                                   "//div[2]/div[1]/div/div[2]/div/div/div/form//select")
    select11.click()

    # 35. Click 'MAT-MR-.YYYY.-'
    mat_mr_yyyy_ = driver.find_element(By.XPATH,
                                       "//select[. = 'MAT-MR-.YYYY.-']")
    mat_mr_yyyy_.click()

    # 36. Select the 'Labels' option in 'MAT-MR-.YYYY.-'
    mat_mr_yyyy_ = driver.find_element(By.XPATH,
                                       "//select[. = 'MAT-MR-.YYYY.-']")
    Select(mat_mr_yyyy_).select_by_value("Labels")

    # 37. Click 'MAT-MR-.YYYY.-'
    mat_mr_yyyy_ = driver.find_element(By.XPATH,
                                       "//select[. = 'MAT-MR-.YYYY.-']")
    mat_mr_yyyy_.click()

    # 38. Click 'Update'
    update = driver.find_element(By.XPATH,
                                 "//button[. = 'Update']")
    update.click()

    # 39. Does 'Updated successfully3' contain 'Updated successfully'?
    updated_successfully3 = driver.find_element(By.XPATH,
                                                "//div[. = 'Updated successfully']")
    step_output = updated_successfully3.text
    assert step_output and ("Updated successfully" in step_output)

    # 40. Click 'INPUT38'
    input38 = driver.find_element(By.XPATH,
                                  "//div[2]/div[2]/div[1]/div[1]/div/input")
    input38.click()

    # 41. Click 'SPAN1'
    span1 = driver.find_element(By.XPATH,
                                "//div[3]/div[1]/div/div/div[2]/div[2]/button/span[1]")
    span1.click()

    # 42. Click 'Delete2'
    delete2 = driver.find_element(By.XPATH,
                                  "//a[. = '\n\t\t\t\tDelete']")
    delete2.click()

    # 43. Click 'Yes5'
    yes5 = driver.find_element(By.XPATH,
                               "//button[. = 'Yes']")
    yes5.click()

    # 44. Click 'New6'
    new6 = driver.find_element(By.XPATH,
                               "//span[. = 'New']")
    new6.click()

    # 45. Click 'INPUT11'
    input11 = driver.find_element(By.XPATH,
                                  "//div[2]/form/div[1]//input")
    input11.click()

    # 46. Click '311'
    _311 = driver.find_element(By.XPATH,
                               "//div[1]/div[1]/div/div/div[. = '31']")
    _311.click()

    # 47. Scroll window by ('0','100')
    driver.execute_script("window.scrollBy(0,100)")

    # 48. Click 'DIV'
    div = driver.find_element(By.XPATH,
                              "//div[2]/div/div[2]/div[2]/div[1]/div/div/div[2]")
    div.click()

    # 49. Type 'epi' in 'Item Code'
    item_code = driver.find_element(By.XPATH,
                                    "//input[@placeholder = 'Item Code']")
    item_code.send_keys("epi")

    # 50. Click 'P33'
    p33 = driver.find_element(By.XPATH,
                              "//div[2]/div[1]/div/div/div/ul/li[1]/a/p[1]")
    p33.click()

    # 51. Click 'For Warehouse'
    for_warehouse = driver.find_element(By.XPATH,
                                        "//input[@placeholder = 'For Warehouse']")
    for_warehouse.click()

    # 52. Click 'EPI-Warehouse2 - EIPL'
    epi_warehouse2_eipl = driver.find_element(By.XPATH,
                                              "//strong[. = 'EPI-Warehouse2 - EIPL']")
    epi_warehouse2_eipl.click()

    # 53. Click 'Save'
    save = driver.find_element(By.XPATH,
                               "//span[. = 'Save']")
    save.click()

    # 54. Scroll window by ('0','-100')
    driver.execute_script("window.scrollBy(0,-100)")

    # 55. Does 'Saved3' contain 'Saved'?
    saved3 = driver.find_element(By.XPATH,
                                 "//div[3]/div[. = 'Saved']")
    step_output = saved3.text
    assert step_output and ("Saved" in step_output)

    # 56. Click 'Submit'
    submit = driver.find_element(By.XPATH,
                                 "//button/span[. = 'Submit']")
    submit.click()

    # 57. Click 'Yes4'
    yes4 = driver.find_element(By.XPATH,
                               "//div[2]/div/div//button[. = 'Yes']")
    yes4.click()

    # 58. Does 'Saved13' contain 'Saved'?
    saved13 = driver.find_element(By.XPATH,
                                  "//div[4]/div[. = 'Saved']")
    step_output = saved13.text
    assert step_output and ("Saved" in step_output)
